-- Additional PostgreSQL compatibility layer for the legacy SQL Server routines that were still pending.
-- Load after database/postgres/legacy_mirror.sql and database/postgres/legacy_programmable_compat.sql.

CREATE SCHEMA IF NOT EXISTS dbo;

-- -----------------------------------------------------------------------------
-- Additional inferred support objects for promotions, coupons and backup requests
-- -----------------------------------------------------------------------------

ALTER TABLE dbo."REFERENCIAS_MAYORISTAS"
  ADD COLUMN IF NOT EXISTS "EsReferencia" smallint NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "Cantidad" integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "PorcentajeDescuento" numeric(24,2) NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS dbo."REGLASCONVENIOS" (
  "ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IDREGLA" bigint NOT NULL,
  "TIPOCONVENIO" integer NOT NULL,
  "Activa" smallint NOT NULL DEFAULT 1
);
COMMENT ON TABLE dbo."REGLASCONVENIOS" IS 'Inferred compatibility table. Columns reconstructed from SQL module usage.';
CREATE INDEX IF NOT EXISTS "IX_REGLASCONVENIOS_IDREGLA" ON dbo."REGLASCONVENIOS" ("IDREGLA");
CREATE INDEX IF NOT EXISTS "IX_REGLASCONVENIOS_TIPOCONVENIO" ON dbo."REGLASCONVENIOS" ("TIPOCONVENIO");

CREATE TABLE IF NOT EXISTS dbo."TABLA_PARAMETROS" (
  "Columna" varchar(100) PRIMARY KEY,
  "Valor" varchar(500) NOT NULL DEFAULT ''
);
COMMENT ON TABLE dbo."TABLA_PARAMETROS" IS 'Inferred compatibility table. Columns reconstructed from SQL module usage.';

CREATE TABLE IF NOT EXISTS dbo."CUPONES" (
  "IdCupon" integer PRIMARY KEY,
  "Nombre" varchar(50) NOT NULL DEFAULT '',
  "Tipo" integer NOT NULL DEFAULT 0,
  "UsaCodigo" integer NOT NULL DEFAULT 0,
  "Acumulativo" integer NOT NULL DEFAULT 0,
  "UsaReferencias" integer NOT NULL DEFAULT 0,
  "FechaInicial" timestamp(0) without time zone,
  "FechaFinal" timestamp(0) without time zone,
  "FechaCanjeInicial" timestamp(0) without time zone,
  "FechaCanjeFinal" timestamp(0) without time zone,
  "MontoDesde" numeric(15,2) NOT NULL DEFAULT 0,
  "MontoHasta" numeric(15,2) NOT NULL DEFAULT 0,
  "Mensaje" varchar(500) NOT NULL DEFAULT '',
  "ProductosActivan" integer NOT NULL DEFAULT 0,
  "MinimoCantidad" integer NOT NULL DEFAULT 0,
  "Status" smallint NOT NULL DEFAULT 1
);
COMMENT ON TABLE dbo."CUPONES" IS 'Inferred compatibility table. Columns reconstructed from SQL module usage.';
CREATE INDEX IF NOT EXISTS "IX_CUPONES_Status_Fechas" ON dbo."CUPONES" ("Status", "FechaInicial", "FechaFinal");

CREATE TABLE IF NOT EXISTS dbo."CODIGOSCONVENIOS" (
  "IdCodigo" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Codigo" varchar(10) NOT NULL,
  "IdCupon" integer NOT NULL,
  "Status" smallint NOT NULL DEFAULT 1
);
COMMENT ON TABLE dbo."CODIGOSCONVENIOS" IS 'Inferred compatibility table. Columns reconstructed from SQL module usage.';
CREATE UNIQUE INDEX IF NOT EXISTS "UX_CODIGOSCONVENIOS_Codigo" ON dbo."CODIGOSCONVENIOS" ("Codigo");
CREATE INDEX IF NOT EXISTS "IX_CODIGOSCONVENIOS_IdCupon_Status" ON dbo."CODIGOSCONVENIOS" ("IdCupon", "Status");

CREATE TABLE IF NOT EXISTS dbo."TRANSACCIONESCUPONES" (
  "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "NumeroFactura" bigint NOT NULL,
  "Serie" varchar(15) NOT NULL,
  "Fecha" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "MontoFactura" numeric(15,2) NOT NULL DEFAULT 0,
  "IdCupon" integer NOT NULL,
  "CodigoConvenio" varchar(10),
  "Cliente" varchar(20),
  "FechaCanjeInicial" timestamp(0) without time zone,
  "FechaCanjeFinal" timestamp(0) without time zone,
  "Acumula" integer NOT NULL DEFAULT 0
);
COMMENT ON TABLE dbo."TRANSACCIONESCUPONES" IS 'Inferred compatibility table. Columns reconstructed from SQL module usage.';
CREATE INDEX IF NOT EXISTS "IX_TRANSACCIONESCUPONES_Factura" ON dbo."TRANSACCIONESCUPONES" ("NumeroFactura", "Serie");

CREATE TABLE IF NOT EXISTS dbo."grupo_cupones" (
  "Referencia" varchar(10) NOT NULL,
  "CodigoMarca" varchar(3) NOT NULL,
  "ProductosActivan" varchar(10) NOT NULL
);
COMMENT ON TABLE dbo."grupo_cupones" IS 'Inferred compatibility table. Columns reconstructed from SQL module usage.';
CREATE INDEX IF NOT EXISTS "IX_grupo_cupones_ref_marca" ON dbo."grupo_cupones" ("Referencia", "CodigoMarca", "ProductosActivan");

CREATE TABLE IF NOT EXISTS dbo."RESPALDOS_PENDIENTES" (
  "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "BaseDatos" varchar(150) NOT NULL,
  "NombreDispositivo" varchar(200) NOT NULL,
  "UbicacionArchivo" text NOT NULL,
  "FechaSolicitud" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "Estado" varchar(30) NOT NULL DEFAULT 'PENDING',
  "Observacion" text
);
COMMENT ON TABLE dbo."RESPALDOS_PENDIENTES" IS 'PostgreSQL compatibility queue for the legacy SQL Server backup procedure.';

-- -----------------------------------------------------------------------------
-- Helper routines
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION dbo."_compat_normalize_table_name"(p_name text)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT regexp_replace(replace(replace(trim(coalesce(p_name, '')), '[', ''), ']', ''), '^.*\.', '');
$$;

CREATE OR REPLACE FUNCTION dbo."_compat_resolve_table"(p_name text)
RETURNS regclass
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
  v_raw text := trim(coalesce(p_name, ''));
  v_clean text := dbo."_compat_normalize_table_name"(p_name);
  v_rel regclass;
BEGIN
  IF v_raw = '' THEN
    RETURN NULL;
  END IF;

  v_rel := to_regclass(v_raw);
  IF v_rel IS NOT NULL THEN
    RETURN v_rel;
  END IF;

  IF v_clean = '' THEN
    RETURN NULL;
  END IF;

  v_rel := to_regclass(format('pg_temp.%I', v_clean));
  IF v_rel IS NOT NULL THEN
    RETURN v_rel;
  END IF;

  v_rel := to_regclass(format('dbo.%I', v_clean));
  IF v_rel IS NOT NULL THEN
    RETURN v_rel;
  END IF;

  v_rel := to_regclass(format('public.%I', v_clean));
  RETURN v_rel;
END;
$$;

CREATE OR REPLACE FUNCTION dbo."_compat_rule_active_today"(
  p_lunes smallint,
  p_martes smallint,
  p_miercoles smallint,
  p_jueves smallint,
  p_viernes smallint,
  p_sabado smallint,
  p_domingo smallint
)
RETURNS boolean
LANGUAGE sql
STABLE
AS $$
  SELECT CASE extract(isodow FROM current_date)::integer
    WHEN 1 THEN coalesce(p_lunes, 0) = 1
    WHEN 2 THEN coalesce(p_martes, 0) = 1
    WHEN 3 THEN coalesce(p_miercoles, 0) = 1
    WHEN 4 THEN coalesce(p_jueves, 0) = 1
    WHEN 5 THEN coalesce(p_viernes, 0) = 1
    WHEN 6 THEN coalesce(p_sabado, 0) = 1
    ELSE coalesce(p_domingo, 0) = 1
  END;
$$;

CREATE OR REPLACE FUNCTION dbo."_compat_ensure_result_table"(p_name text)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  v_name text := dbo."_compat_normalize_table_name"(p_name);
  v_rel regclass;
BEGIN
  IF v_name = '' THEN
    RAISE EXCEPTION 'Nombre de tabla resultado vacio';
  END IF;

  v_rel := dbo."_compat_resolve_table"(p_name);
  IF v_rel IS NULL THEN
    EXECUTE format(
      'CREATE TEMP TABLE %I (
         codigobarra varchar(15) NOT NULL,
         tipolista varchar(3) NOT NULL,
         preciolista numeric(24,4) NOT NULL DEFAULT 0,
         precio numeric(24,2) NOT NULL DEFAULT 0,
         cantidad numeric(24,4) NOT NULL DEFAULT 0,
         impuesto numeric(24,4) NOT NULL DEFAULT 0,
         porcentajeimpuesto numeric(24,2) NOT NULL DEFAULT 0,
         costo numeric(24,2) NOT NULL DEFAULT 0,
         porcentajedescuento numeric(7,4) NOT NULL DEFAULT 0,
         regla varchar(50),
         idregla bigint
       ) ON COMMIT PRESERVE ROWS',
      v_name
    );
    EXECUTE format('CREATE INDEX %I ON %I (codigobarra)', 'ix_' || v_name || '_codigobarra', v_name);
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION dbo."_compat_load_temp_facturacion_pasoa"(p_tablafacturacion text)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  v_source regclass;
BEGIN
  v_source := dbo."_compat_resolve_table"(p_tablafacturacion);
  IF v_source IS NULL THEN
    RAISE EXCEPTION 'Tabla de facturacion no encontrada: %', p_tablafacturacion;
  END IF;

  DROP TABLE IF EXISTS pg_temp.temp_facturacion_pasoa;
  CREATE TEMP TABLE pg_temp.temp_facturacion_pasoa (
    codigobarra varchar(15) NOT NULL,
    tipolista varchar(3) NOT NULL,
    preciolista numeric(24,4) NOT NULL DEFAULT 0,
    precio numeric(24,2) NOT NULL DEFAULT 0,
    cantidad numeric(24,4) NOT NULL DEFAULT 0,
    impuesto numeric(24,4) NOT NULL DEFAULT 0,
    porcentajeimpuesto numeric(24,2) NOT NULL DEFAULT 0,
    costo numeric(24,2) NOT NULL DEFAULT 0,
    porcentajedescuento numeric(7,4) NOT NULL DEFAULT 0
  ) ON COMMIT DROP;
  CREATE INDEX ON pg_temp.temp_facturacion_pasoa (codigobarra);

  EXECUTE format(
    'INSERT INTO pg_temp.temp_facturacion_pasoa (codigobarra, tipolista, preciolista, precio, cantidad, impuesto, porcentajeimpuesto, costo, porcentajedescuento)
     SELECT codigobarra, tipolista, coalesce(preciolista, 0), coalesce(precio, 0), coalesce(cantidad, 0),
            coalesce(impuesto, 0), coalesce(porcentajeimpuesto, 0), coalesce(costo, 0), coalesce(porcentajedescuento, 0)
     FROM %s',
    v_source
  );
END;
$$;

CREATE OR REPLACE FUNCTION dbo."_compat_reset_temp_facturacion"()
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
  DROP TABLE IF EXISTS pg_temp.temp_facturacion;
  CREATE TEMP TABLE pg_temp.temp_facturacion (
    item integer NOT NULL,
    codigobarra varchar(15) NOT NULL,
    tipolista varchar(3) NOT NULL,
    preciolista numeric(24,4) NOT NULL DEFAULT 0,
    precio numeric(24,2) NOT NULL DEFAULT 0,
    cantidad numeric(24,4) NOT NULL DEFAULT 1,
    impuesto numeric(24,4) NOT NULL DEFAULT 0,
    porcentajeimpuesto numeric(24,2) NOT NULL DEFAULT 0,
    costo numeric(24,2) NOT NULL DEFAULT 0,
    porcentajedescuento numeric(7,4) NOT NULL DEFAULT 0,
    agrupacion varchar(1)
  ) ON COMMIT DROP;
  CREATE INDEX ON pg_temp.temp_facturacion (item);
  CREATE INDEX ON pg_temp.temp_facturacion (codigobarra);
END;
$$;

CREATE OR REPLACE FUNCTION dbo."_compat_upsert_pasoa"(
  p_codigobarra varchar(15),
  p_tipolista varchar(3),
  p_preciolista numeric(24,4),
  p_precio numeric(24,2),
  p_cantidad numeric(24,4),
  p_impuesto numeric(24,4),
  p_porcentajeimpuesto numeric(24,2),
  p_costo numeric(24,2),
  p_porcentajedescuento numeric(7,4)
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  v_rows integer;
BEGIN
  UPDATE pg_temp.temp_facturacion_pasoa
  SET cantidad = coalesce(cantidad, 0) + coalesce(p_cantidad, 0)
  WHERE codigobarra = p_codigobarra
    AND tipolista = p_tipolista
    AND coalesce(preciolista, 0) = coalesce(p_preciolista, 0)
    AND coalesce(precio, 0) = coalesce(p_precio, 0)
    AND coalesce(impuesto, 0) = coalesce(p_impuesto, 0)
    AND coalesce(porcentajeimpuesto, 0) = coalesce(p_porcentajeimpuesto, 0)
    AND coalesce(costo, 0) = coalesce(p_costo, 0)
    AND coalesce(porcentajedescuento, 0) = coalesce(p_porcentajedescuento, 0);

  GET DIAGNOSTICS v_rows = ROW_COUNT;
  IF v_rows = 0 THEN
    INSERT INTO pg_temp.temp_facturacion_pasoa (
      codigobarra, tipolista, preciolista, precio, cantidad, impuesto, porcentajeimpuesto, costo, porcentajedescuento
    ) VALUES (
      p_codigobarra, p_tipolista, coalesce(p_preciolista, 0), coalesce(p_precio, 0), coalesce(p_cantidad, 0),
      coalesce(p_impuesto, 0), coalesce(p_porcentajeimpuesto, 0), coalesce(p_costo, 0), coalesce(p_porcentajedescuento, 0)
    );
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION dbo."_compat_upsert_result"(
  p_table text,
  p_codigobarra varchar(15),
  p_tipolista varchar(3),
  p_preciolista numeric(24,4),
  p_precio numeric(24,2),
  p_cantidad numeric(24,4),
  p_impuesto numeric(24,4),
  p_porcentajeimpuesto numeric(24,2),
  p_costo numeric(24,2),
  p_porcentajedescuento numeric(7,4),
  p_regla varchar(50),
  p_idregla bigint
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  v_rel regclass;
  v_rows integer;
BEGIN
  PERFORM dbo."_compat_ensure_result_table"(p_table);
  v_rel := dbo."_compat_resolve_table"(p_table);

  EXECUTE format(
    'UPDATE %s
     SET cantidad = coalesce(cantidad, 0) + $1
     WHERE codigobarra = $2
       AND tipolista = $3
       AND coalesce(preciolista, 0) = coalesce($4, 0)
       AND coalesce(precio, 0) = coalesce($5, 0)
       AND coalesce(impuesto, 0) = coalesce($6, 0)
       AND coalesce(porcentajeimpuesto, 0) = coalesce($7, 0)
       AND coalesce(costo, 0) = coalesce($8, 0)
       AND coalesce(porcentajedescuento, 0) = coalesce($9, 0)
       AND coalesce(regla, '''') = coalesce($10, '''')
       AND coalesce(idregla, 0) = coalesce($11, 0)',
    v_rel
  )
  USING coalesce(p_cantidad, 0), p_codigobarra, p_tipolista, coalesce(p_preciolista, 0), coalesce(p_precio, 0),
        coalesce(p_impuesto, 0), coalesce(p_porcentajeimpuesto, 0), coalesce(p_costo, 0), coalesce(p_porcentajedescuento, 0),
        p_regla, p_idregla;

  GET DIAGNOSTICS v_rows = ROW_COUNT;
  IF v_rows = 0 THEN
    EXECUTE format(
      'INSERT INTO %s (codigobarra, tipolista, preciolista, precio, cantidad, impuesto, porcentajeimpuesto, costo, porcentajedescuento, regla, idregla)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)',
      v_rel
    )
    USING p_codigobarra, p_tipolista, coalesce(p_preciolista, 0), coalesce(p_precio, 0), coalesce(p_cantidad, 0),
          coalesce(p_impuesto, 0), coalesce(p_porcentajeimpuesto, 0), coalesce(p_costo, 0), coalesce(p_porcentajedescuento, 0),
          p_regla, p_idregla;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION dbo."_compat_calcular_descuento"(
  p_precio numeric(24,2),
  p_porcdesc numeric(24,2),
  p_preciovalor numeric(24,2),
  p_tiporegla integer
)
RETURNS TABLE(nuevo_precio numeric(24,2), nuevo_porcentaje numeric(7,4))
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
  v_tasa numeric(24,4);
  v_target numeric(24,4);
BEGIN
  IF coalesce(p_tiporegla, 0) = 0 THEN
    nuevo_precio := round(coalesce(p_precio, 0) - (coalesce(p_precio, 0) * coalesce(p_porcdesc, 0) / 100.0), 2);
    nuevo_porcentaje := round(coalesce(p_porcdesc, 0), 4);
    RETURN NEXT;
    RETURN;
  END IF;

  v_tasa := coalesce(dbo."UltimaTasaCambio"(), 1);
  v_target := round(coalesce(p_preciovalor, 0) * v_tasa, 2);
  nuevo_precio := least(coalesce(p_precio, 0), v_target);
  IF coalesce(p_precio, 0) <= 0 OR coalesce(p_precio, 0) <= v_target THEN
    nuevo_porcentaje := 0;
  ELSE
    nuevo_porcentaje := round((((coalesce(p_precio, 0) - v_target) / p_precio) * 100.0)::numeric, 4);
  END IF;
  RETURN NEXT;
END;
$$;

CREATE OR REPLACE FUNCTION dbo."PromocionesYOfertas_DevolverRemanente"()
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  v_row record;
BEGIN
  IF to_regclass('pg_temp.temp_facturacion') IS NULL OR to_regclass('pg_temp.temp_facturacion_pasoa') IS NULL THEN
    RETURN;
  END IF;

  FOR v_row IN
    SELECT *
    FROM pg_temp.temp_facturacion
    ORDER BY item
  LOOP
    PERFORM dbo."_compat_upsert_pasoa"(
      v_row.codigobarra,
      v_row.tipolista,
      v_row.preciolista,
      v_row.precio,
      1,
      v_row.impuesto,
      v_row.porcentajeimpuesto,
      v_row.costo,
      v_row.porcentajedescuento
    );
  END LOOP;

  DELETE FROM pg_temp.temp_facturacion;
END;
$$;

CREATE OR REPLACE FUNCTION dbo."PromocionesYOfertas_InsertarRestosFacturacion"(p_tablaresultado varchar(50))
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  v_row record;
BEGIN
  IF to_regclass('pg_temp.temp_facturacion_pasoa') IS NULL THEN
    RETURN;
  END IF;

  FOR v_row IN
    SELECT *
    FROM pg_temp.temp_facturacion_pasoa
  LOOP
    PERFORM dbo."_compat_upsert_result"(
      p_tablaresultado,
      v_row.codigobarra,
      v_row.tipolista,
      v_row.preciolista,
      v_row.precio,
      v_row.cantidad,
      v_row.impuesto,
      v_row.porcentajeimpuesto,
      v_row.costo,
      v_row.porcentajedescuento,
      NULL,
      NULL
    );
  END LOOP;
END;
$$;


CREATE OR REPLACE FUNCTION dbo."PromocionesYOfertas_DescuentoEnSiMismo"(
  p_id_regla integer,
  p_lleve integer,
  p_pague integer,
  p_porcdesc numeric(5,2),
  p_grupo integer,
  p_imprimir varchar(15),
  p_tablafacturacion varchar(50),
  p_tablaresultado varchar(50),
  p_convenio varchar(4),
  p_preciovalor numeric(24,2),
  p_tiporegla integer
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  v_row record;
  v_desc record;
  v_contador integer;
  v_ciclo integer;
BEGIN
  IF p_lleve <= 0 THEN
    RETURN;
  END IF;

  PERFORM dbo."_compat_reset_temp_facturacion"();
  INSERT INTO pg_temp.temp_facturacion (
    item, codigobarra, tipolista, preciolista, precio, cantidad, impuesto, porcentajeimpuesto, costo, porcentajedescuento, agrupacion
  )
  SELECT row_number() OVER (ORDER BY precio ASC, codigobarra ASC, cantidad ASC),
         codigobarra, tipolista, preciolista, precio, 1, impuesto, porcentajeimpuesto, costo, porcentajedescuento, NULL
  FROM (
    SELECT f.codigobarra, f.tipolista, f.preciolista, f.precio, f.impuesto, f.porcentajeimpuesto, f.costo, f.porcentajedescuento, f.cantidad
    FROM pg_temp.temp_facturacion_pasoa f
    INNER JOIN dbo."fntPrendasGrupoRegla"(p_grupo) g
      ON g."CodigoBarra" = f.codigobarra
     AND g."IDGrupoRegla" = p_grupo
    , generate_series(1, GREATEST(CEIL(coalesce(f.cantidad, 0))::integer, 0)) gs(n)
  ) expanded;

  SELECT count(*) INTO v_contador FROM pg_temp.temp_facturacion;
  v_ciclo := 0;
  WHILE v_contador >= p_lleve LOOP
    v_ciclo := v_ciclo + 1;
    SELECT * INTO v_row FROM pg_temp.temp_facturacion ORDER BY item DESC LIMIT 1;
    EXIT WHEN NOT FOUND;

    SELECT * INTO v_desc
    FROM dbo."_compat_calcular_descuento"(v_row.precio, p_porcdesc, p_preciovalor, p_tiporegla);

    PERFORM dbo."_compat_upsert_result"(
      p_tablaresultado,
      v_row.codigobarra,
      'R',
      v_desc.nuevo_precio,
      v_row.precio,
      1,
      v_row.impuesto,
      v_row.porcentajeimpuesto,
      v_row.costo,
      v_desc.nuevo_porcentaje,
      p_imprimir,
      p_id_regla
    );

    DELETE FROM pg_temp.temp_facturacion WHERE item = v_row.item;

    IF p_convenio IN ('1', '2') AND v_ciclo >= p_pague THEN
      EXIT;
    END IF;

    IF v_ciclo >= p_lleve THEN
      v_ciclo := 0;
      SELECT count(*) INTO v_contador FROM pg_temp.temp_facturacion;
    END IF;
  END LOOP;

  DELETE FROM pg_temp.temp_facturacion_pasoa
  WHERE codigobarra IN (
    SELECT "CodigoBarra" FROM dbo."fntPrendasGrupoRegla"(p_grupo)
  );

  PERFORM dbo."PromocionesYOfertas_DevolverRemanente"();
END;
$$;

CREATE OR REPLACE FUNCTION dbo."PromocionesYOfertas_DescuentoGeneralEnSiMismo"(
  p_id_regla integer,
  p_lleve integer,
  p_pague integer,
  p_porcdesc numeric(5,2),
  p_grupo integer,
  p_imprimir varchar(15),
  p_tablafacturacion varchar(50),
  p_tablaresultado varchar(50),
  p_convenio varchar(4),
  p_preciovalor numeric(24,2),
  p_tiporegla integer
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  v_row record;
  v_desc record;
  v_contador integer;
  v_ciclo integer;
BEGIN
  IF p_lleve <= 0 THEN
    RETURN;
  END IF;

  PERFORM dbo."_compat_reset_temp_facturacion"();
  INSERT INTO pg_temp.temp_facturacion (
    item, codigobarra, tipolista, preciolista, precio, cantidad, impuesto, porcentajeimpuesto, costo, porcentajedescuento, agrupacion
  )
  SELECT row_number() OVER (ORDER BY precio ASC, codigobarra ASC, cantidad ASC),
         codigobarra, tipolista, preciolista, precio, 1, impuesto, porcentajeimpuesto, costo, porcentajedescuento, NULL
  FROM (
    SELECT f.codigobarra, f.tipolista, f.preciolista, f.precio, f.impuesto, f.porcentajeimpuesto, f.costo, f.porcentajedescuento, f.cantidad
    FROM pg_temp.temp_facturacion_pasoa f
    , generate_series(1, GREATEST(CEIL(coalesce(f.cantidad, 0))::integer, 0)) gs(n)
  ) expanded;

  SELECT count(*) INTO v_contador FROM pg_temp.temp_facturacion;
  v_ciclo := 0;
  WHILE v_contador >= p_lleve LOOP
    v_ciclo := v_ciclo + 1;
    SELECT * INTO v_row FROM pg_temp.temp_facturacion ORDER BY item DESC LIMIT 1;
    EXIT WHEN NOT FOUND;

    SELECT * INTO v_desc
    FROM dbo."_compat_calcular_descuento"(v_row.precio, p_porcdesc, p_preciovalor, p_tiporegla);

    PERFORM dbo."_compat_upsert_result"(
      p_tablaresultado,
      v_row.codigobarra,
      'R',
      v_desc.nuevo_precio,
      v_row.precio,
      1,
      v_row.impuesto,
      v_row.porcentajeimpuesto,
      v_row.costo,
      v_desc.nuevo_porcentaje,
      p_imprimir,
      p_id_regla
    );

    DELETE FROM pg_temp.temp_facturacion WHERE item = v_row.item;

    IF v_ciclo >= p_lleve THEN
      v_ciclo := 0;
      SELECT count(*) INTO v_contador FROM pg_temp.temp_facturacion;
    END IF;
  END LOOP;

  DELETE FROM pg_temp.temp_facturacion_pasoa
  WHERE codigobarra NOT IN (SELECT "CodigoBarra" FROM dbo."CODIGOS_RECARGOS");

  PERFORM dbo."PromocionesYOfertas_DevolverRemanente"();
END;
$$;

CREATE OR REPLACE FUNCTION dbo."PromocionesYOfertas_DescuentosMismoGrupo"(
  p_id_regla integer,
  p_lleve integer,
  p_pague integer,
  p_porcdesc numeric(5,2),
  p_grupo integer,
  p_imprimir varchar(15),
  p_tablafacturacion varchar(50),
  p_tablaresultado varchar(50),
  p_convenio varchar(4),
  p_preciovalor numeric(24,2),
  p_tiporegla integer
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  v_row record;
  v_desc record;
  v_contador integer;
  v_ciclo integer;
BEGIN
  IF p_lleve <= 0 THEN
    RETURN;
  END IF;

  PERFORM dbo."_compat_reset_temp_facturacion"();
  INSERT INTO pg_temp.temp_facturacion (
    item, codigobarra, tipolista, preciolista, precio, cantidad, impuesto, porcentajeimpuesto, costo, porcentajedescuento, agrupacion
  )
  SELECT row_number() OVER (ORDER BY precio ASC, codigobarra ASC, cantidad ASC),
         codigobarra, tipolista, preciolista, precio, 1, impuesto, porcentajeimpuesto, costo, porcentajedescuento, NULL
  FROM (
    SELECT f.codigobarra, f.tipolista, f.preciolista, f.precio, f.impuesto, f.porcentajeimpuesto, f.costo, f.porcentajedescuento, f.cantidad
    FROM pg_temp.temp_facturacion_pasoa f
    INNER JOIN dbo."fntPrendasGrupoRegla"(p_grupo) g
      ON g."CodigoBarra" = f.codigobarra
     AND g."IDGrupoRegla" = p_grupo
    , generate_series(1, GREATEST(CEIL(coalesce(f.cantidad, 0))::integer, 0)) gs(n)
  ) expanded;

  SELECT count(*) INTO v_contador FROM pg_temp.temp_facturacion;
  WHILE v_contador >= p_lleve LOOP
    v_ciclo := 0;

    WHILE v_ciclo < p_pague LOOP
      SELECT * INTO v_row FROM pg_temp.temp_facturacion ORDER BY item DESC LIMIT 1;
      EXIT WHEN NOT FOUND;

      PERFORM dbo."_compat_upsert_result"(
        p_tablaresultado,
        v_row.codigobarra,
        'R',
        v_row.precio,
        v_row.precio,
        1,
        v_row.impuesto,
        v_row.porcentajeimpuesto,
        v_row.costo,
        0,
        p_imprimir,
        p_id_regla
      );
      DELETE FROM pg_temp.temp_facturacion WHERE item = v_row.item;
      v_ciclo := v_ciclo + 1;
    END LOOP;

    WHILE v_ciclo < p_lleve LOOP
      SELECT * INTO v_row FROM pg_temp.temp_facturacion ORDER BY item ASC LIMIT 1;
      EXIT WHEN NOT FOUND;

      SELECT * INTO v_desc
      FROM dbo."_compat_calcular_descuento"(v_row.precio, p_porcdesc, p_preciovalor, p_tiporegla);

      PERFORM dbo."_compat_upsert_result"(
        p_tablaresultado,
        v_row.codigobarra,
        'R',
        v_desc.nuevo_precio,
        v_row.precio,
        1,
        v_row.impuesto,
        v_row.porcentajeimpuesto,
        v_row.costo,
        v_desc.nuevo_porcentaje,
        p_imprimir,
        p_id_regla
      );
      DELETE FROM pg_temp.temp_facturacion WHERE item = v_row.item;
      v_ciclo := v_ciclo + 1;
    END LOOP;

    IF p_convenio IN ('1', '2') AND v_ciclo >= p_lleve THEN
      EXIT;
    END IF;

    SELECT count(*) INTO v_contador FROM pg_temp.temp_facturacion;
  END LOOP;

  DELETE FROM pg_temp.temp_facturacion_pasoa
  WHERE codigobarra IN (
    SELECT "CodigoBarra" FROM dbo."fntPrendasGrupoRegla"(p_grupo)
  );

  PERFORM dbo."PromocionesYOfertas_DevolverRemanente"();
END;
$$;

CREATE OR REPLACE FUNCTION dbo."PromocionesYOfertas_DescuentoGeneralMismoGrupo"(
  p_id_regla integer,
  p_lleve integer,
  p_pague integer,
  p_porcdesc numeric(5,2),
  p_grupo integer,
  p_imprimir varchar(15),
  p_tablafacturacion varchar(50),
  p_tablaresultado varchar(50),
  p_convenio varchar(4),
  p_preciovalor numeric(24,2),
  p_tiporegla integer
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  v_row record;
  v_desc record;
  v_contador integer;
  v_ciclo integer;
BEGIN
  IF p_lleve <= 0 THEN
    RETURN;
  END IF;

  PERFORM dbo."_compat_reset_temp_facturacion"();
  INSERT INTO pg_temp.temp_facturacion (
    item, codigobarra, tipolista, preciolista, precio, cantidad, impuesto, porcentajeimpuesto, costo, porcentajedescuento, agrupacion
  )
  SELECT row_number() OVER (ORDER BY precio ASC, codigobarra ASC, cantidad ASC),
         codigobarra, tipolista, preciolista, precio, 1, impuesto, porcentajeimpuesto, costo, porcentajedescuento, NULL
  FROM (
    SELECT f.codigobarra, f.tipolista, f.preciolista, f.precio, f.impuesto, f.porcentajeimpuesto, f.costo, f.porcentajedescuento, f.cantidad
    FROM pg_temp.temp_facturacion_pasoa f
    , generate_series(1, GREATEST(CEIL(coalesce(f.cantidad, 0))::integer, 0)) gs(n)
    WHERE NOT EXISTS (
      SELECT 1 FROM dbo."CODIGOS_RECARGOS" cr WHERE cr."CodigoBarra" = f.codigobarra
    )
  ) expanded;

  SELECT count(*) INTO v_contador FROM pg_temp.temp_facturacion;
  WHILE v_contador >= p_lleve LOOP
    v_ciclo := 0;

    WHILE v_ciclo < p_pague LOOP
      SELECT * INTO v_row FROM pg_temp.temp_facturacion ORDER BY item DESC LIMIT 1;
      EXIT WHEN NOT FOUND;

      PERFORM dbo."_compat_upsert_result"(
        p_tablaresultado,
        v_row.codigobarra,
        'R',
        v_row.precio,
        v_row.precio,
        1,
        v_row.impuesto,
        v_row.porcentajeimpuesto,
        v_row.costo,
        0,
        p_imprimir,
        p_id_regla
      );
      DELETE FROM pg_temp.temp_facturacion WHERE item = v_row.item;
      v_ciclo := v_ciclo + 1;
    END LOOP;

    WHILE v_ciclo < p_lleve LOOP
      SELECT * INTO v_row FROM pg_temp.temp_facturacion ORDER BY item ASC LIMIT 1;
      EXIT WHEN NOT FOUND;

      SELECT * INTO v_desc
      FROM dbo."_compat_calcular_descuento"(v_row.precio, p_porcdesc, p_preciovalor, p_tiporegla);

      PERFORM dbo."_compat_upsert_result"(
        p_tablaresultado,
        v_row.codigobarra,
        'R',
        CASE WHEN coalesce(p_tiporegla, 0) = 0 THEN v_desc.nuevo_precio ELSE p_preciovalor END,
        v_row.precio,
        1,
        v_row.impuesto,
        v_row.porcentajeimpuesto,
        v_row.costo,
        v_desc.nuevo_porcentaje,
        p_imprimir,
        p_id_regla
      );
      DELETE FROM pg_temp.temp_facturacion WHERE item = v_row.item;
      v_ciclo := v_ciclo + 1;
    END LOOP;

    SELECT count(*) INTO v_contador FROM pg_temp.temp_facturacion;
  END LOOP;

  DELETE FROM pg_temp.temp_facturacion_pasoa
  WHERE codigobarra NOT IN (SELECT "CodigoBarra" FROM dbo."CODIGOS_RECARGOS");

  PERFORM dbo."PromocionesYOfertas_DevolverRemanente"();
END;
$$;

CREATE OR REPLACE FUNCTION dbo."PromocionesYOfertas_DescuentosDistintoGrupo"(
  p_id_regla integer,
  p_lleve integer,
  p_pague integer,
  p_porcdesc numeric(5,2),
  p_grupoa integer,
  p_grupob integer,
  p_imprimir varchar(15),
  p_tablafacturacion varchar(50),
  p_tablaresultado varchar(50),
  p_convenio varchar(4),
  p_preciovalor numeric(24,2),
  p_tiporegla integer
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  v_row record;
  v_desc record;
  v_contabc integer;
  v_contac integer;
  v_contbc integer;
  v_ciclo integer;
BEGIN
  IF p_lleve <= 0 THEN
    RETURN;
  END IF;

  PERFORM dbo."_compat_reset_temp_facturacion"();

  INSERT INTO pg_temp.temp_facturacion (
    item, codigobarra, tipolista, preciolista, precio, cantidad, impuesto, porcentajeimpuesto, costo, porcentajedescuento, agrupacion
  )
  SELECT row_number() OVER (ORDER BY agrupacion, precio ASC, codigobarra ASC),
         codigobarra, tipolista, preciolista, precio, GREATEST(coalesce(cantidad, 0), 1), impuesto, porcentajeimpuesto, costo, porcentajedescuento, agrupacion
  FROM (
    SELECT f.codigobarra, f.tipolista, f.preciolista, f.precio, f.impuesto, f.porcentajeimpuesto, f.costo, f.porcentajedescuento, f.cantidad,
           CASE
             WHEN EXISTS (SELECT 1 FROM dbo."fntPrendasGrupoRegla"(p_grupoa) ga WHERE ga."CodigoBarra" = f.codigobarra)
              AND EXISTS (SELECT 1 FROM dbo."fntPrendasGrupoRegla"(p_grupob) gb WHERE gb."CodigoBarra" = f.codigobarra) THEN 'C'
             WHEN EXISTS (SELECT 1 FROM dbo."fntPrendasGrupoRegla"(p_grupoa) ga WHERE ga."CodigoBarra" = f.codigobarra) THEN 'A'
             WHEN EXISTS (SELECT 1 FROM dbo."fntPrendasGrupoRegla"(p_grupob) gb WHERE gb."CodigoBarra" = f.codigobarra) THEN 'B'
             ELSE NULL
           END AS agrupacion
    FROM pg_temp.temp_facturacion_pasoa f
  ) expanded
  WHERE agrupacion IS NOT NULL;

  SELECT count(*),
         count(*) FILTER (WHERE agrupacion IN ('A', 'C')),
         count(*) FILTER (WHERE agrupacion IN ('B', 'C'))
    INTO v_contabc, v_contac, v_contbc
  FROM pg_temp.temp_facturacion;

  WHILE v_contabc >= p_lleve AND v_contac >= p_pague AND v_contbc >= greatest(p_lleve - p_pague, 0) LOOP
    v_ciclo := 0;

    WHILE v_ciclo < p_pague LOOP
      SELECT * INTO v_row
      FROM pg_temp.temp_facturacion
      WHERE agrupacion IN ('A', 'C')
      ORDER BY item DESC
      LIMIT 1;
      EXIT WHEN NOT FOUND;

      PERFORM dbo."_compat_upsert_result"(
        p_tablaresultado,
        v_row.codigobarra,
        'R',
        v_row.precio,
        v_row.precio,
        1,
        v_row.impuesto,
        v_row.porcentajeimpuesto,
        v_row.costo,
        0,
        p_imprimir,
        p_id_regla
      );
      DELETE FROM pg_temp.temp_facturacion WHERE item = v_row.item;
      v_ciclo := v_ciclo + 1;
    END LOOP;

    WHILE v_ciclo < p_lleve LOOP
      SELECT * INTO v_row
      FROM pg_temp.temp_facturacion
      WHERE agrupacion IN ('B', 'C')
      ORDER BY item ASC
      LIMIT 1;
      EXIT WHEN NOT FOUND;

      SELECT * INTO v_desc
      FROM dbo."_compat_calcular_descuento"(v_row.precio, p_porcdesc, p_preciovalor, p_tiporegla);

      PERFORM dbo."_compat_upsert_result"(
        p_tablaresultado,
        v_row.codigobarra,
        'R',
        v_desc.nuevo_precio,
        v_row.precio,
        1,
        v_row.impuesto,
        v_row.porcentajeimpuesto,
        v_row.costo,
        v_desc.nuevo_porcentaje,
        p_imprimir,
        p_id_regla
      );
      DELETE FROM pg_temp.temp_facturacion WHERE item = v_row.item;
      v_ciclo := v_ciclo + 1;
    END LOOP;

    IF p_convenio IN ('1', '2') THEN
      EXIT;
    END IF;

    SELECT count(*),
           count(*) FILTER (WHERE agrupacion IN ('A', 'C')),
           count(*) FILTER (WHERE agrupacion IN ('B', 'C'))
      INTO v_contabc, v_contac, v_contbc
    FROM pg_temp.temp_facturacion;
  END LOOP;

  DELETE FROM pg_temp.temp_facturacion_pasoa
  WHERE codigobarra IN (
    SELECT "CodigoBarra" FROM dbo."fntPrendasGrupoRegla"(p_grupoa)
    UNION
    SELECT "CodigoBarra" FROM dbo."fntPrendasGrupoRegla"(p_grupob)
  );

  PERFORM dbo."PromocionesYOfertas_DevolverRemanente"();
END;
$$;

CREATE OR REPLACE FUNCTION dbo."PromocionesYOfertas_DescuentoCatalogo"(
  p_id_regla integer,
  p_lleve integer,
  p_pague integer,
  p_porcdesc numeric(5,2),
  p_grupo integer,
  p_imprimir varchar(15),
  p_tablafacturacion varchar(50),
  p_tablaresultado varchar(50),
  p_convenio varchar(10),
  p_preciovalor numeric(24,2),
  p_tiporegla integer
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  v_row record;
  v_montoref numeric(24,2) := 0;
  v_tbase numeric(24,2) := 0;
  v_timpuesto numeric(24,2) := 0;
  v_incluirimp boolean := false;
  v_descpct numeric(24,2) := 0;
  v_contador integer;
BEGIN
  PERFORM dbo."_compat_reset_temp_facturacion"();
  INSERT INTO pg_temp.temp_facturacion (
    item, codigobarra, tipolista, preciolista, precio, cantidad, impuesto, porcentajeimpuesto, costo, porcentajedescuento, agrupacion
  )
  SELECT row_number() OVER (ORDER BY precio ASC, codigobarra ASC, cantidad ASC),
         codigobarra, tipolista, preciolista, precio, 1, impuesto, porcentajeimpuesto, costo, porcentajedescuento, NULL
  FROM (
    SELECT f.codigobarra,
           f.tipolista,
           f.preciolista,
           coalesce(i."PrecioDetal", f.precio) AS precio,
           coalesce((i."PrecioDetal" * imp."PorcentajeImpuesto" / 100.0), f.impuesto) AS impuesto,
           f.porcentajeimpuesto,
           f.costo,
           f.porcentajedescuento,
           f.cantidad
    FROM pg_temp.temp_facturacion_pasoa f
    LEFT JOIN dbo."INVENTARIO" i ON i."CodigoBarra" = f.codigobarra
    LEFT JOIN dbo."IMPUESTOS" imp ON imp."Codigo" = i."TipoImpuesto"
    , generate_series(1, GREATEST(CEIL(coalesce(f.cantidad, 0))::integer, 0)) gs(n)
  ) expanded;

  SELECT coalesce(sum(precio), 0), coalesce(sum(impuesto), 0)
    INTO v_tbase, v_timpuesto
  FROM pg_temp.temp_facturacion;

  SELECT EXISTS (
    SELECT 1
    FROM dbo."TABLA_VALORES"
    WHERE "IdTabla" = 'IncluirIVADescCat'
      AND upper(trim("Descripcion")) = 'TRUE'
  ) INTO v_incluirimp;

  IF v_incluirimp THEN
    v_montoref := v_tbase + v_timpuesto;
  ELSE
    v_montoref := v_tbase;
  END IF;

  SELECT coalesce(dm."PorcentajeDescuento", 0)
    INTO v_descpct
  FROM dbo."DESCUENTO_MAYORISTA" dm
  WHERE dm."MontoMinimo" <= v_montoref
  ORDER BY dm."MontoMinimo" DESC
  LIMIT 1;

  SELECT count(*) INTO v_contador FROM pg_temp.temp_facturacion;
  WHILE v_contador >= 1 LOOP
    SELECT * INTO v_row FROM pg_temp.temp_facturacion ORDER BY item ASC LIMIT 1;
    EXIT WHEN NOT FOUND;

    PERFORM dbo."_compat_upsert_result"(
      p_tablaresultado,
      v_row.codigobarra,
      'M',
      round(v_row.precio - (v_row.precio * coalesce(v_descpct, 0) / 100.0), 4),
      v_row.precio,
      1,
      v_row.impuesto,
      v_row.porcentajeimpuesto,
      v_row.costo,
      coalesce(v_descpct, 0),
      '',
      0
    );

    DELETE FROM pg_temp.temp_facturacion WHERE item = v_row.item;
    SELECT count(*) INTO v_contador FROM pg_temp.temp_facturacion;
  END LOOP;

  DELETE FROM pg_temp.temp_facturacion_pasoa
  WHERE codigobarra NOT IN (SELECT "CodigoBarra" FROM dbo."CODIGOS_RECARGOS");

  PERFORM dbo."PromocionesYOfertas_DevolverRemanente"();
END;
$$;

CREATE OR REPLACE FUNCTION dbo."PromocionesYOfertas_Descuento_MAYORISTAS"(
  p_codreferencia varchar(18),
  p_esreferencia integer,
  p_lleve integer,
  p_descuento numeric(24,2),
  p_tablafacturacion varchar(50),
  p_tablaresultado varchar(50)
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  v_row record;
  v_contador integer;
BEGIN
  IF p_lleve <= 0 THEN
    RETURN;
  END IF;

  PERFORM dbo."_compat_reset_temp_facturacion"();
  INSERT INTO pg_temp.temp_facturacion (
    item, codigobarra, tipolista, preciolista, precio, cantidad, impuesto, porcentajeimpuesto, costo, porcentajedescuento, agrupacion
  )
  SELECT row_number() OVER (ORDER BY precio ASC, codigobarra ASC, cantidad ASC),
         codigobarra, tipolista, preciolista, precio, GREATEST(coalesce(cantidad, 0), 1), impuesto, porcentajeimpuesto, costo, porcentajedescuento, NULL
  FROM (
    SELECT f.codigobarra, f.tipolista, f.preciolista, f.precio, f.impuesto, f.porcentajeimpuesto, f.costo, f.porcentajedescuento, f.cantidad
    FROM pg_temp.temp_facturacion_pasoa f
    WHERE (
      (coalesce(p_esreferencia, 0) = 1 AND f.codigobarra IN (
        SELECT i."CodigoBarra"
        FROM dbo."INVENTARIO" i
        WHERE trim(i."Referencia") || trim(i."CodigoMarca") = p_codreferencia
      ))
      OR (coalesce(p_esreferencia, 0) = 0 AND f.codigobarra = p_codreferencia)
    )
      AND f.codigobarra NOT IN (
        SELECT rm."Codigo" FROM dbo."REFERENCIAS_MAYORISTAS" rm WHERE rm."EsExcepcion" = 1
      )
  ) expanded;

  SELECT count(*) INTO v_contador FROM pg_temp.temp_facturacion;
  IF v_contador >= p_lleve THEN
    WHILE v_contador >= 1 LOOP
      SELECT * INTO v_row FROM pg_temp.temp_facturacion ORDER BY item ASC LIMIT 1;
      EXIT WHEN NOT FOUND;

      PERFORM dbo."_compat_upsert_result"(
        p_tablaresultado,
        v_row.codigobarra,
        'T',
        round(v_row.precio - (v_row.precio * coalesce(p_descuento, 0) / 100.0), 4),
        v_row.precio,
        1,
        v_row.impuesto,
        v_row.porcentajeimpuesto,
        v_row.costo,
        coalesce(p_descuento, 0),
        'MAYORISTA',
        0
      );

      DELETE FROM pg_temp.temp_facturacion WHERE item = v_row.item;
      SELECT count(*) INTO v_contador FROM pg_temp.temp_facturacion;
    END LOOP;
  END IF;

  IF coalesce(p_esreferencia, 0) = 1 THEN
    DELETE FROM pg_temp.temp_facturacion_pasoa
    WHERE codigobarra IN (
      SELECT i."CodigoBarra"
      FROM dbo."INVENTARIO" i
      WHERE trim(i."Referencia") || trim(i."CodigoMarca") = p_codreferencia
    );
  ELSE
    DELETE FROM pg_temp.temp_facturacion_pasoa WHERE codigobarra = p_codreferencia;
  END IF;

  PERFORM dbo."PromocionesYOfertas_DevolverRemanente"();
END;
$$;


CREATE OR REPLACE FUNCTION dbo."PromocionesYOfertas_SelectorDeReglas_Convenios"(
  p_tablafacturacion varchar(50),
  p_tablaresultado varchar(50),
  p_convenio varchar(4)
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  v_rule record;
  v_descuentogeneral integer;
BEGIN
  FOR v_rule IN
    SELECT DISTINCT r.*
    FROM dbo."REGLAS" r
    INNER JOIN dbo."REGLASCONVENIOS" c
      ON c."IDREGLA" = r."ID"
    WHERE r."Activa" = 0
      AND c."Activa" = 1
      AND c."TIPOCONVENIO" = coalesce(nullif(p_convenio, ''), '0')::integer
      AND current_date BETWEEN r."FechaInicio" AND r."FechaFin"
      AND current_time BETWEEN r."HoraInicio" AND r."HoraFin"
      AND dbo."_compat_rule_active_today"(r."Lunes", r."Martes", r."Miercoles", r."Jueves", r."Viernes", r."Sabado", r."Domingo")
      AND EXISTS (
        SELECT 1
        FROM pg_temp.temp_facturacion_pasoa f
        INNER JOIN dbo."fntPrendasGrupoRegla"(r."ProductosActivan"::integer) g
          ON g."CodigoBarra" = f.codigobarra
      )
    ORDER BY r."Prioridad", r."ID"
    LIMIT CASE WHEN p_convenio IN ('1', '2') THEN 1 ELSE 2147483647 END
  LOOP
    SELECT count(*) INTO v_descuentogeneral
    FROM dbo."GRUPO_REGLAS"
    WHERE "IDGrupoRegla" = v_rule."ProductosActivan"
      AND "CodigoBarra" = '+++';

    IF v_rule."Lleve" = v_rule."Pague" AND v_rule."ProductosActivan" = v_rule."ProductosAfectados" AND v_descuentogeneral <> 0 THEN
      PERFORM dbo."PromocionesYOfertas_DescuentoGeneralEnSiMismo"(v_rule."ID"::integer, v_rule."Lleve", v_rule."Pague", coalesce(v_rule."PorcDescuento", 0), v_rule."ProductosActivan"::integer, v_rule."Imprimir", p_tablafacturacion, p_tablaresultado, p_convenio, v_rule."Precio", v_rule."Tipo");
    ELSIF v_rule."Lleve" <> v_rule."Pague" AND v_rule."ProductosActivan" = v_rule."ProductosAfectados" AND v_descuentogeneral <> 0 THEN
      PERFORM dbo."PromocionesYOfertas_DescuentoGeneralMismoGrupo"(v_rule."ID"::integer, v_rule."Lleve", v_rule."Pague", coalesce(v_rule."PorcDescuento", 0), v_rule."ProductosActivan"::integer, v_rule."Imprimir", p_tablafacturacion, p_tablaresultado, p_convenio, v_rule."Precio", v_rule."Tipo");
    ELSIF v_rule."Lleve" <> v_rule."Pague" AND v_rule."ProductosActivan" = v_rule."ProductosAfectados" AND v_descuentogeneral = 0 THEN
      PERFORM dbo."PromocionesYOfertas_DescuentosMismoGrupo"(v_rule."ID"::integer, v_rule."Lleve", v_rule."Pague", coalesce(v_rule."PorcDescuento", 0), v_rule."ProductosActivan"::integer, v_rule."Imprimir", p_tablafacturacion, p_tablaresultado, p_convenio, v_rule."Precio", v_rule."Tipo");
    ELSIF v_rule."Lleve" <> v_rule."Pague" AND v_rule."ProductosActivan" <> v_rule."ProductosAfectados" AND v_descuentogeneral = 0 THEN
      PERFORM dbo."PromocionesYOfertas_DescuentosDistintoGrupo"(v_rule."ID"::integer, v_rule."Lleve", v_rule."Pague", coalesce(v_rule."PorcDescuento", 0), v_rule."ProductosActivan"::integer, v_rule."ProductosAfectados"::integer, v_rule."Imprimir", p_tablafacturacion, p_tablaresultado, p_convenio, v_rule."Precio", v_rule."Tipo");
    ELSIF v_rule."Lleve" = v_rule."Pague" AND v_rule."ProductosActivan" = v_rule."ProductosAfectados" AND v_descuentogeneral = 0 THEN
      PERFORM dbo."PromocionesYOfertas_DescuentoEnSiMismo"(v_rule."ID"::integer, v_rule."Lleve", v_rule."Pague", coalesce(v_rule."PorcDescuento", 0), v_rule."ProductosActivan"::integer, v_rule."Imprimir", p_tablafacturacion, p_tablaresultado, p_convenio, v_rule."Precio", v_rule."Tipo");
    END IF;
  END LOOP;
END;
$$;

CREATE OR REPLACE FUNCTION dbo."PromocionesYOfertas_SelectorDeReglas"(
  p_tablafacturacion varchar(50),
  p_tablaresultado varchar(50),
  p_convenio varchar(4),
  p_escredito varchar(1),
  p_esmayorista varchar(1) DEFAULT NULL,
  p_grupo integer DEFAULT NULL
)
RETURNS TABLE(
  "CodigoBarra" varchar(15),
  "Nombre" text,
  "Precio" numeric(24,2),
  "Cantidad" numeric(24,4),
  "PrecioLista" numeric(24,4),
  "Descuento" numeric(24,4),
  "TotalDescuento" numeric(24,4),
  "Impuesto" numeric(24,4),
  "TotalImpuesto" numeric(24,4),
  "PorcentajeImpuesto" numeric(24,2),
  "Costo" numeric(24,2),
  "TotalCosto" numeric(24,4),
  "Referencia" varchar(10),
  "CodigoMarca" varchar(3),
  "PorcentajeDescuento" numeric(7,4),
  "Regla" varchar(50),
  "IDRegla" bigint,
  "TipoLista" varchar(3)
)
LANGUAGE plpgsql
AS $$
DECLARE
  v_rule record;
  v_descuentogeneral integer;
  v_result regclass;
  v_ref record;
BEGIN
  PERFORM dbo."_compat_ensure_result_table"(p_tablaresultado);
  PERFORM dbo."_compat_load_temp_facturacion_pasoa"(p_tablafacturacion);

  IF upper(coalesce(p_esmayorista, 'N')) = 'S' THEN
    PERFORM dbo."PromocionesYOfertas_DescuentoCatalogo"(0, 0, 0, 0, 0, '', p_tablafacturacion, p_tablaresultado, '', 0, 0);
  END IF;

  IF coalesce(p_convenio, '0') <> '0' THEN
    PERFORM dbo."PromocionesYOfertas_SelectorDeReglas_Convenios"(p_tablafacturacion, p_tablaresultado, p_convenio);
  END IF;

  FOR v_rule IN
    SELECT DISTINCT r.*
    FROM dbo."REGLAS" r
    WHERE r."Activa" = 0
      AND current_date BETWEEN r."FechaInicio" AND r."FechaFin"
      AND current_time BETWEEN r."HoraInicio" AND r."HoraFin"
      AND dbo."_compat_rule_active_today"(r."Lunes", r."Martes", r."Miercoles", r."Jueves", r."Viernes", r."Sabado", r."Domingo")
      AND (coalesce(p_grupo, 0) = 0 OR r."ProductosActivan" = p_grupo)
      AND EXISTS (
        SELECT 1
        FROM pg_temp.temp_facturacion_pasoa f
        INNER JOIN dbo."fntPrendasGrupoRegla"(r."ProductosActivan"::integer) g
          ON g."CodigoBarra" = f.codigobarra
      )
    ORDER BY r."Prioridad", r."ID"
  LOOP
    SELECT count(*) INTO v_descuentogeneral
    FROM dbo."GRUPO_REGLAS"
    WHERE "IDGrupoRegla" = v_rule."ProductosActivan"
      AND "CodigoBarra" = '+++';

    IF v_rule."Lleve" = v_rule."Pague" AND v_rule."ProductosActivan" = v_rule."ProductosAfectados" AND v_descuentogeneral <> 0 THEN
      PERFORM dbo."PromocionesYOfertas_DescuentoGeneralEnSiMismo"(v_rule."ID"::integer, v_rule."Lleve", v_rule."Pague", coalesce(v_rule."PorcDescuento", 0), v_rule."ProductosActivan"::integer, v_rule."Imprimir", p_tablafacturacion, p_tablaresultado, '0', v_rule."Precio", v_rule."Tipo");
    ELSIF v_rule."Lleve" <> v_rule."Pague" AND v_rule."ProductosActivan" = v_rule."ProductosAfectados" AND v_descuentogeneral <> 0 THEN
      PERFORM dbo."PromocionesYOfertas_DescuentoGeneralMismoGrupo"(v_rule."ID"::integer, v_rule."Lleve", v_rule."Pague", coalesce(v_rule."PorcDescuento", 0), v_rule."ProductosActivan"::integer, v_rule."Imprimir", p_tablafacturacion, p_tablaresultado, '0', v_rule."Precio", v_rule."Tipo");
    ELSIF v_rule."Lleve" <> v_rule."Pague" AND v_rule."ProductosActivan" = v_rule."ProductosAfectados" AND v_descuentogeneral = 0 THEN
      PERFORM dbo."PromocionesYOfertas_DescuentosMismoGrupo"(v_rule."ID"::integer, v_rule."Lleve", v_rule."Pague", coalesce(v_rule."PorcDescuento", 0), v_rule."ProductosActivan"::integer, v_rule."Imprimir", p_tablafacturacion, p_tablaresultado, '0', v_rule."Precio", v_rule."Tipo");
    ELSIF v_rule."Lleve" <> v_rule."Pague" AND v_rule."ProductosActivan" <> v_rule."ProductosAfectados" AND v_descuentogeneral = 0 THEN
      PERFORM dbo."PromocionesYOfertas_DescuentosDistintoGrupo"(v_rule."ID"::integer, v_rule."Lleve", v_rule."Pague", coalesce(v_rule."PorcDescuento", 0), v_rule."ProductosActivan"::integer, v_rule."ProductosAfectados"::integer, v_rule."Imprimir", p_tablafacturacion, p_tablaresultado, '0', v_rule."Precio", v_rule."Tipo");
    ELSIF v_rule."Lleve" = v_rule."Pague" AND v_rule."ProductosActivan" = v_rule."ProductosAfectados" AND v_descuentogeneral = 0 THEN
      PERFORM dbo."PromocionesYOfertas_DescuentoEnSiMismo"(v_rule."ID"::integer, v_rule."Lleve", v_rule."Pague", coalesce(v_rule."PorcDescuento", 0), v_rule."ProductosActivan"::integer, v_rule."Imprimir", p_tablafacturacion, p_tablaresultado, '0', v_rule."Precio", v_rule."Tipo");
    END IF;
  END LOOP;

  FOR v_ref IN
    SELECT DISTINCT rm."Codigo", rm."EsReferencia", rm."Cantidad", rm."PorcentajeDescuento"
    FROM dbo."REFERENCIAS_MAYORISTAS" rm
    WHERE rm."EsExcepcion" = 0
  LOOP
    PERFORM dbo."PromocionesYOfertas_Descuento_MAYORISTAS"(v_ref."Codigo", v_ref."EsReferencia", v_ref."Cantidad", v_ref."PorcentajeDescuento", p_tablafacturacion, p_tablaresultado);
  END LOOP;

  PERFORM dbo."PromocionesYOfertas_InsertarRestosFacturacion"(p_tablaresultado);

  v_result := dbo."_compat_resolve_table"(p_tablaresultado);
  RETURN QUERY EXECUTE format(
    'SELECT r.codigobarra::varchar(15),
            i."Nombre"::text,
            r.precio::numeric(24,2),
            r.cantidad::numeric(24,4),
            r.preciolista::numeric(24,4),
            (r.precio - r.preciolista)::numeric(24,4) AS descuento,
            (r.cantidad * (r.precio - r.preciolista))::numeric(24,4) AS totaldescuento,
            ((r.preciolista * r.porcentajeimpuesto) / 100.0)::numeric(24,4) AS impuesto,
            (r.cantidad * ((r.preciolista * r.porcentajeimpuesto) / 100.0))::numeric(24,4) AS totalimpuesto,
            r.porcentajeimpuesto::numeric(24,2),
            coalesce(i."CostoPromedio", r.costo)::numeric(24,2) AS costo,
            (coalesce(i."CostoPromedio", r.costo) * r.cantidad)::numeric(24,4) AS totalcosto,
            i."Referencia"::varchar(10),
            i."CodigoMarca"::varchar(3),
            r.porcentajedescuento::numeric(7,4),
            r.regla::varchar(50),
            r.idregla::bigint,
            r.tipolista::varchar(3)
     FROM %s r
     INNER JOIN dbo."INVENTARIO" i ON i."CodigoBarra" = r.codigobarra',
    v_result
  );
END;
$$;

CREATE OR REPLACE FUNCTION dbo."Selector_Reglas"(
  p_tablafacturacion varchar(50),
  p_convenio varchar(4)
)
RETURNS TABLE(
  "Prioridad" bigint,
  "Regla" varchar(15),
  "Descripcion" varchar(250),
  "Porc" numeric(7,4),
  "Precio" numeric(10,2),
  "Lleve" integer,
  "Pague" integer,
  "ProductosActivan" bigint
)
LANGUAGE plpgsql
AS $$
DECLARE
  v_source regclass;
  v_cantidadreglas integer := 2;
BEGIN
  v_source := dbo."_compat_resolve_table"(p_tablafacturacion);
  IF v_source IS NULL THEN
    RETURN;
  END IF;

  DROP TABLE IF EXISTS pg_temp.temp_selector_reglas;
  CREATE TEMP TABLE pg_temp.temp_selector_reglas (
    prioridad bigint NOT NULL,
    productosactivan bigint NOT NULL,
    imprimir varchar(15) NOT NULL,
    descripcion varchar(250) NOT NULL,
    porcdescuento numeric(7,4) NOT NULL,
    precio numeric(10,2) NOT NULL,
    lleve integer NOT NULL,
    pague integer NOT NULL
  ) ON COMMIT DROP;

  EXECUTE format(
    'INSERT INTO pg_temp.temp_selector_reglas (prioridad, productosactivan, imprimir, descripcion, porcdescuento, precio, lleve, pague)
     SELECT r."Prioridad", r."ProductosActivan", r."Imprimir", r."Descripcion", r."PorcDescuento", r."Precio", r."Lleve", r."Pague"
     FROM %s f
     CROSS JOIN LATERAL dbo."fntReglasPrenda"(f.codigobarra, coalesce(nullif($1, ''''), ''0'')::smallint) r',
    v_source
  ) USING p_convenio;

  IF EXISTS (
    SELECT 1
    FROM dbo."TABLA_PARAMETROS" tp
    WHERE tp."Columna" = 'FACT_Regla_No_Aplicar'
      AND upper(trim(tp."Valor")) = 'TRUE'
  ) THEN
    v_cantidadreglas := 1;
    INSERT INTO pg_temp.temp_selector_reglas (prioridad, productosactivan, imprimir, descripcion, porcdescuento, precio, lleve, pague)
    VALUES (0, -1, 'No Aplicar', 'No Aplicar', 0, 0, 0, 0);
  END IF;

  IF (SELECT count(*) FROM pg_temp.temp_selector_reglas) >= v_cantidadreglas THEN
    INSERT INTO pg_temp.temp_selector_reglas (prioridad, productosactivan, imprimir, descripcion, porcdescuento, precio, lleve, pague)
    VALUES (0, 0, 'General', 'Reglas Generales', 0, 0, 0, 0);

    RETURN QUERY
    SELECT prioridad, imprimir::varchar(15), descripcion::varchar(250), porcdescuento::numeric(7,4), precio::numeric(10,2), lleve, pague, productosactivan
    FROM pg_temp.temp_selector_reglas
    GROUP BY prioridad, productosactivan, imprimir, descripcion, porcdescuento, precio, lleve, pague
    ORDER BY prioridad;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION dbo."Cupones_SelectorDeImpresion"(
  p_monto numeric(15,2),
  p_cliente varchar(20),
  p_numerofactura bigint,
  p_tablaresultado varchar(30),
  p_serie varchar(15)
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  v_result regclass;
  v_cupon record;
  v_codigo_convenio varchar(10);
  v_id_convenio bigint;
  v_validar boolean;
  v_validar_ref boolean;
  v_monto1 numeric(15,2);
  v_cantidad_ref numeric(15,2);
  v_secuencia integer;
BEGIN
  v_result := dbo."_compat_resolve_table"(p_tablaresultado);
  IF v_result IS NULL THEN
    RETURN;
  END IF;

  DROP TABLE IF EXISTS pg_temp.temp_impresion_bono;
  CREATE TEMP TABLE pg_temp.temp_impresion_bono (
    codigobarra varchar(15),
    tipolista varchar(3),
    preciolista numeric(18,4),
    precio numeric(18,4),
    cantidad numeric(18,4),
    impuesto numeric(18,4),
    porcentajeimpuesto numeric(18,4),
    costo numeric(18,4),
    porcentajedescuento numeric(7,4),
    idregla integer,
    regla varchar(15)
  ) ON COMMIT DROP;

  EXECUTE format(
    'INSERT INTO pg_temp.temp_impresion_bono (codigobarra, tipolista, preciolista, precio, cantidad, impuesto, porcentajeimpuesto, costo, porcentajedescuento, idregla, regla)
     SELECT codigobarra, tipolista, preciolista, precio, cantidad, impuesto, porcentajeimpuesto, costo, porcentajedescuento, coalesce(idregla, 0), regla
     FROM %s',
    v_result
  );

  FOR v_cupon IN
    SELECT *
    FROM dbo."CUPONES"
    WHERE "Status" = 1
      AND current_date BETWEEN coalesce("FechaInicial"::date, current_date) AND coalesce("FechaFinal"::date, current_date)
  LOOP
    v_validar := false;
    v_validar_ref := false;
    v_monto1 := 0;
    v_cantidad_ref := 0;
    v_secuencia := 0;
    v_codigo_convenio := NULL;
    v_id_convenio := NULL;

    IF coalesce(v_cupon."UsaReferencias", 0) = 1 THEN
      SELECT coalesce(sum((t.precio + t.impuesto) * t.cantidad), 0), coalesce(sum(t.cantidad), 0)
        INTO v_monto1, v_cantidad_ref
      FROM pg_temp.temp_impresion_bono t
      INNER JOIN dbo."INVENTARIO" i ON i."CodigoBarra" = t.codigobarra
      INNER JOIN dbo."grupo_cupones" g
        ON i."Referencia" = g."Referencia"
       AND i."CodigoMarca" = g."CodigoMarca"
      WHERE g."ProductosActivan" = v_cupon."ProductosActivan"::varchar(10);

      v_validar_ref := v_monto1 BETWEEN coalesce(v_cupon."MontoDesde", 0) AND coalesce(v_cupon."MontoHasta", 0)
                       AND v_cantidad_ref >= coalesce(v_cupon."MinimoCantidad", 0);
    ELSE
      SELECT coalesce(sum(t.cantidad), 0)
        INTO v_cantidad_ref
      FROM pg_temp.temp_impresion_bono t
      WHERE t.codigobarra NOT IN (SELECT "CodigoBarra" FROM dbo."CODIGOS_RECARGOS");

      v_validar_ref := p_monto BETWEEN coalesce(v_cupon."MontoDesde", 0) AND coalesce(v_cupon."MontoHasta", 0)
                       AND v_cantidad_ref >= coalesce(v_cupon."MinimoCantidad", 0);
    END IF;

    IF coalesce(v_cupon."UsaCodigo", 0) = 1 THEN
      SELECT c."Codigo", c."IdCodigo"
        INTO v_codigo_convenio, v_id_convenio
      FROM dbo."CODIGOSCONVENIOS" c
      WHERE c."Status" = 1
        AND c."IdCupon" = v_cupon."IdCupon"
      ORDER BY c."IdCodigo"
      LIMIT 1;

      IF coalesce(v_codigo_convenio, '') <> '' AND v_validar_ref THEN
        v_validar := true;
        UPDATE dbo."CODIGOSCONVENIOS"
        SET "Status" = 2
        WHERE "IdCodigo" = v_id_convenio;
      END IF;
    ELSE
      v_validar := true;
    END IF;

    IF coalesce(v_cupon."Acumulativo", 0) = 1 THEN
      v_secuencia := CASE v_cupon."Tipo"
        WHEN 2 THEN floor((CASE WHEN coalesce(v_cupon."UsaReferencias", 0) = 1 AND v_validar_ref THEN nullif(v_monto1, 0) ELSE nullif(p_monto, 0) END) / NULLIF(v_cupon."MontoDesde", 0))::integer
        WHEN 6 THEN floor(p_monto / 1000)::integer
        WHEN 3 THEN floor(p_monto / NULLIF(v_cupon."MontoDesde", 0))::integer * 3
        WHEN 4 THEN floor(p_monto / NULLIF(v_cupon."MontoDesde", 0))::integer * 4
        ELSE 0
      END;
    END IF;

    IF v_validar AND v_validar_ref THEN
      INSERT INTO dbo."TRANSACCIONESCUPONES" (
        "NumeroFactura", "Serie", "Fecha", "MontoFactura", "IdCupon", "CodigoConvenio", "Cliente", "FechaCanjeInicial", "FechaCanjeFinal", "Acumula"
      ) VALUES (
        p_numerofactura, p_serie, CURRENT_TIMESTAMP, p_monto, v_cupon."IdCupon", v_codigo_convenio, p_cliente,
        v_cupon."FechaCanjeInicial", v_cupon."FechaCanjeFinal", coalesce(v_secuencia, 0)
      );
    END IF;
  END LOOP;
END;
$$;

CREATE OR REPLACE FUNCTION dbo."RespaldoBD"(
  p_bd varchar(150),
  p_nombredispositivo varchar(200),
  p_ubicacionnombrefisico text
)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
  INSERT INTO dbo."RESPALDOS_PENDIENTES" (
    "BaseDatos", "NombreDispositivo", "UbicacionArchivo", "Estado", "Observacion"
  ) VALUES (
    p_bd,
    p_nombredispositivo,
    p_ubicacionnombrefisico,
    CASE WHEN current_database() = p_bd THEN 'PENDING' ELSE 'DATABASE_MISMATCH' END,
    'Compatibilidad PostgreSQL: SQL Server BACKUP DATABASE no existe dentro del motor. Use pg_dump o pg_basebackup fuera de SQL.'
  );

  RAISE NOTICE 'RespaldoBD compat: solicitud registrada en dbo."RESPALDOS_PENDIENTES". PostgreSQL requiere pg_dump/pg_basebackup fuera de SQL.';
END;
$$;

CREATE OR REPLACE FUNCTION dbo."PROCESAR_MOVITRAN"(
  p_strxml text,
  p_strproceso varchar(50),
  p_creararticulo varchar(2) DEFAULT NULL
)
RETURNS TABLE(
  "Categoria" text,
  "CodigoBarra" varchar(15),
  "Nombre" text,
  "Cantidad" numeric(24,4),
  "Referencia" varchar(10),
  "CodigoMarca" varchar(3),
  "Mensaje" text
)
LANGUAGE plpgsql
AS $$
DECLARE
  v_xml_text text;
  v_xml xml;
  v_crear text := upper(coalesce(p_creararticulo, 'NO'));
BEGIN
  v_xml_text := replace(coalesce(p_strxml, ''), '<xml xmlns:rs="urn:schemas-microsoft-com:rowset" xmlns:z="#RowsetSchema">', '<?xml version="1.0" encoding="ISO-8859-1"?><root>');
  v_xml_text := replace(v_xml_text, 'rs:data', 'root');
  v_xml_text := replace(v_xml_text, 'z:row', 'MOVITRAN');
  v_xml_text := replace(v_xml_text, '</xml>', '</root>');
  IF position('<?xml' IN v_xml_text) = 0 THEN
    v_xml_text := '<?xml version="1.0" encoding="UTF-8"?><root>' || v_xml_text || '</root>';
  END IF;

  v_xml := xmlparse(document v_xml_text);

  DROP TABLE IF EXISTS pg_temp.temp_movitran_xml;
  CREATE TEMP TABLE pg_temp.temp_movitran_xml AS
  SELECT coalesce(nullif(trim(codbarra), ''), nullif(trim(codbarraant), ''))::varchar(15) AS codigobarra,
         trim(nomb)::varchar(60) AS nombre,
         coalesce(cant, canti, 0)::numeric(24,4) AS cantidad,
         trim(refer)::varchar(10) AS referencia,
         trim(marc)::varchar(3) AS codigomarca,
         trim(nombmarca)::varchar(20) AS nombremarca,
         trim(talla)::varchar(3) AS talla,
         trim(color)::varchar(3) AS codigocolor,
         trim(nombcolor)::varchar(30) AS nombrecolor,
         trim(fabricante)::varchar(12) AS codigofabricante,
         trim(nombfabric)::varchar(50) AS nombrefabricante,
         trim(categoria)::varchar(6) AS codigocategoria,
         trim(nombcateg)::varchar(60) AS nombrecategoria,
         numt::numeric(18,0) AS numerotransferencia,
         trim(numtra)::varchar(15) AS codigobarraant
  FROM XMLTABLE('/root/MOVITRAN'
    PASSING v_xml
    COLUMNS
      codbarra text PATH '@CODBARRA',
      codbarraant text PATH '@CODBARRAANT',
      nomb text PATH '@NOMB',
      cant numeric PATH '@CANT',
      canti numeric PATH '@CANTI',
      refer text PATH '@REFER',
      marc text PATH '@MARC',
      nombmarca text PATH '@NOMBMARCA',
      talla text PATH '@TALLA',
      color text PATH '@COLOR',
      nombcolor text PATH '@NOMBCOLOR',
      fabricante text PATH '@FABRICANTE',
      nombfabric text PATH '@NOMBFABRIC',
      categoria text PATH '@CATEGORIA',
      nombcateg text PATH '@NOMBCATEG',
      numt numeric PATH '@NUMT',
      numtra text PATH '@NUMTRA'
  ) x;

  IF upper(coalesce(p_strproceso, '')) = 'REMISION' THEN
    RETURN QUERY
    SELECT 'VALIDO'::text,
           x.codigobarra,
           i."Nombre"::text,
           x.cantidad,
           i."Referencia"::varchar(10),
           i."CodigoMarca"::varchar(3),
           NULL::text
    FROM pg_temp.temp_movitran_xml x
    INNER JOIN dbo."INVENTARIO" i ON i."CodigoBarra" = x.codigobarra
    WHERE coalesce(i."CostoPromedio", 0) > 0
      AND coalesce(i."PrecioDetal", 0) > 0
      AND coalesce(i."Status", 0) <> 0;

    RETURN QUERY
    SELECT 'ERROR'::text,
           x.codigobarra,
           x.nombre::text,
           x.cantidad,
           x.referencia,
           x.codigomarca,
           CASE
             WHEN i."CodigoBarra" IS NULL THEN 'Articulo No Existe'
             WHEN coalesce(i."CostoPromedio", 0) <= 0 THEN 'Costo Promedio del Articulo No Valido'
             WHEN coalesce(i."PrecioDetal", 0) <= 0 THEN 'Precio Detal del Articulo No Valido'
             WHEN coalesce(i."Status", 0) = 0 THEN 'Articulo No Activo'
             ELSE 'Articulo No Valido'
           END::text
    FROM pg_temp.temp_movitran_xml x
    LEFT JOIN dbo."INVENTARIO" i ON i."CodigoBarra" = x.codigobarra
    WHERE i."CodigoBarra" IS NULL
       OR coalesce(i."CostoPromedio", 0) <= 0
       OR coalesce(i."PrecioDetal", 0) <= 0
       OR coalesce(i."Status", 0) = 0;
    RETURN;
  END IF;

  IF upper(coalesce(p_strproceso, '')) IN ('COMPRAS', 'IMPORTAR_TRANSFERENCIA') THEN
    IF (v_crear = 'SI' AND upper(coalesce(p_strproceso, '')) = 'COMPRAS') OR upper(coalesce(p_strproceso, '')) = 'IMPORTAR_TRANSFERENCIA' THEN
      INSERT INTO dbo."MARCAS" ("Codigo", "Nombre", "Status")
      SELECT DISTINCT codigomarca, coalesce(nombremarca, codigomarca), 1
      FROM pg_temp.temp_movitran_xml x
      WHERE coalesce(codigomarca, '') <> ''
        AND NOT EXISTS (SELECT 1 FROM dbo."MARCAS" m WHERE m."Codigo" = x.codigomarca);

      INSERT INTO dbo."TALLAS" ("Codigo")
      SELECT DISTINCT talla
      FROM pg_temp.temp_movitran_xml x
      WHERE coalesce(talla, '') <> ''
        AND NOT EXISTS (SELECT 1 FROM dbo."TALLAS" t WHERE t."Codigo" = x.talla);

      INSERT INTO dbo."COLORES" ("Codigo", "Nombre", "Status")
      SELECT DISTINCT codigocolor, coalesce(nombrecolor, codigocolor), 1
      FROM pg_temp.temp_movitran_xml x
      WHERE coalesce(codigocolor, '') <> ''
        AND NOT EXISTS (SELECT 1 FROM dbo."COLORES" c WHERE c."Codigo" = x.codigocolor);

      INSERT INTO dbo."FABRICANTES" ("Codigo", "Nombre", "Status")
      SELECT DISTINCT codigofabricante, coalesce(nombrefabricante, codigofabricante), 1
      FROM pg_temp.temp_movitran_xml x
      WHERE coalesce(codigofabricante, '') <> ''
        AND NOT EXISTS (SELECT 1 FROM dbo."FABRICANTES" f WHERE f."Codigo" = x.codigofabricante);

      INSERT INTO dbo."CATEGORIAS" ("Codigo", "Nombre", "Status")
      SELECT DISTINCT codigocategoria, coalesce(nombrecategoria, codigocategoria), 1
      FROM pg_temp.temp_movitran_xml x
      WHERE coalesce(codigocategoria, '') <> ''
        AND NOT EXISTS (SELECT 1 FROM dbo."CATEGORIAS" c WHERE c."Codigo" = x.codigocategoria);

      INSERT INTO dbo."INVENTARIO" (
        "CodigoBarra", "Referencia", "CodigoMarca", "Nombre", "Talla", "CodigoColor", "Categoria",
        "PrecioDetal", "PrecioMayor", "PrecioAfiliado", "Promocion", "PrecioPromocion", "FechaInicial", "FechaFinal",
        "CostoInicial", "CostoPromedio", "UltimoCosto", "PuntoReorden", "ExistenciaInicial", "Existencia",
        "FechaPrimerMovimiento", "UltimaActualizacion", "Fabricante", "TipoImpuesto", "Tipo", "Nota", "Status", "CodigoBarraAnt"
      )
      SELECT x.codigobarra,
             x.referencia,
             x.codigomarca,
             x.nombre,
             x.talla,
             x.codigocolor,
             coalesce(NULLIF(x.codigocategoria, ''), '00'),
             coalesce((SELECT max(i2."PrecioDetal") FROM dbo."INVENTARIO" i2 WHERE i2."Referencia" = x.referencia AND i2."CodigoMarca" = x.codigomarca AND i2."CodigoBarra" <> x.codigobarra), 0),
             coalesce((SELECT max(i2."PrecioMayor") FROM dbo."INVENTARIO" i2 WHERE i2."Referencia" = x.referencia AND i2."CodigoMarca" = x.codigomarca AND i2."CodigoBarra" <> x.codigobarra), 0),
             coalesce((SELECT max(i2."PrecioAfiliado") FROM dbo."INVENTARIO" i2 WHERE i2."Referencia" = x.referencia AND i2."CodigoMarca" = x.codigomarca AND i2."CodigoBarra" <> x.codigobarra), 0),
             coalesce((SELECT max(i2."Promocion") FROM dbo."INVENTARIO" i2 WHERE i2."Referencia" = x.referencia AND i2."CodigoMarca" = x.codigomarca AND i2."CodigoBarra" <> x.codigobarra), 0),
             coalesce((SELECT max(i2."PrecioPromocion") FROM dbo."INVENTARIO" i2 WHERE i2."Referencia" = x.referencia AND i2."CodigoMarca" = x.codigomarca AND i2."CodigoBarra" <> x.codigobarra), 0),
             coalesce((SELECT max(i2."FechaInicial") FROM dbo."INVENTARIO" i2 WHERE i2."Referencia" = x.referencia AND i2."CodigoMarca" = x.codigomarca AND i2."CodigoBarra" <> x.codigobarra), DATE '2000-01-01'),
             coalesce((SELECT max(i2."FechaFinal") FROM dbo."INVENTARIO" i2 WHERE i2."Referencia" = x.referencia AND i2."CodigoMarca" = x.codigomarca AND i2."CodigoBarra" <> x.codigobarra), DATE '2000-01-01'),
             coalesce((SELECT max(i2."CostoInicial") FROM dbo."INVENTARIO" i2 WHERE i2."Referencia" = x.referencia AND i2."CodigoMarca" = x.codigomarca AND i2."CodigoBarra" <> x.codigobarra), 0),
             coalesce((SELECT max(i2."CostoPromedio") FROM dbo."INVENTARIO" i2 WHERE i2."Referencia" = x.referencia AND i2."CodigoMarca" = x.codigomarca AND i2."CodigoBarra" <> x.codigobarra), 0),
             coalesce((SELECT max(i2."UltimoCosto") FROM dbo."INVENTARIO" i2 WHERE i2."Referencia" = x.referencia AND i2."CodigoMarca" = x.codigomarca AND i2."CodigoBarra" <> x.codigobarra), 0),
             0,
             0,
             0,
             CURRENT_TIMESTAMP,
             CURRENT_TIMESTAMP,
             x.codigofabricante,
             1,
             0,
             '',
             1,
             coalesce(NULLIF(x.codigobarraant, ''), x.codigobarra)
      FROM pg_temp.temp_movitran_xml x
      WHERE x.codigobarra IS NOT NULL
        AND NOT EXISTS (SELECT 1 FROM dbo."INVENTARIO" i WHERE i."CodigoBarra" = x.codigobarra);
    END IF;

    RETURN QUERY
    SELECT CASE WHEN i."CodigoBarra" IS NULL THEN 'CREADO_O_PENDIENTE' ELSE 'EXISTENTE' END::text,
           x.codigobarra,
           coalesce(i."Nombre", x.nombre)::text,
           x.cantidad,
           coalesce(i."Referencia", x.referencia)::varchar(10),
           coalesce(i."CodigoMarca", x.codigomarca)::varchar(3),
           NULL::text
    FROM pg_temp.temp_movitran_xml x
    LEFT JOIN dbo."INVENTARIO" i ON i."CodigoBarra" = x.codigobarra;
    RETURN;
  END IF;

  RETURN QUERY
  SELECT 'RECIBIDO'::text, x.codigobarra, x.nombre::text, x.cantidad, x.referencia, x.codigomarca, NULL::text
  FROM pg_temp.temp_movitran_xml x;
END;
$$;
