-- Best-effort PostgreSQL compatibility layer for legacy SQL Server programmable objects.
-- Load after database/postgres/legacy_mirror.sql.
-- Objects in this file are split in two groups:
--   1. direct translations from the exported T-SQL modules
--   2. inferred support objects for unresolved names that are referenced by those modules
-- Every inferred object is marked with a COMMENT so it can be revisited if the real SQL Server definition appears.

CREATE SCHEMA IF NOT EXISTS dbo;

-- -----------------------------------------------------------------------------
-- Inferred support objects for unresolved dependencies
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS dbo."MOVAJUSTES" (
  "Numero" bigint NOT NULL,
  "CodigoBarra" varchar(15) NOT NULL,
  "Cantidad" numeric(24,4) NOT NULL DEFAULT 0,
  "Costo" numeric(24,8) NOT NULL DEFAULT 0
);
COMMENT ON TABLE dbo."MOVAJUSTES" IS 'Inferred compatibility table. Columns reconstructed from SQL module usage.';
CREATE INDEX IF NOT EXISTS "IX_MOVAJUSTES_Numero" ON dbo."MOVAJUSTES" ("Numero");
CREATE INDEX IF NOT EXISTS "IX_MOVAJUSTES_CodigoBarra" ON dbo."MOVAJUSTES" ("CodigoBarra");

CREATE TABLE IF NOT EXISTS dbo."FISICOLOGICO" (
  "FechaAjuste" date NOT NULL,
  "CodigoBarra" varchar(15) NOT NULL,
  "ConMovimiento" smallint
);
COMMENT ON TABLE dbo."FISICOLOGICO" IS 'Inferred compatibility table. Columns reconstructed from SQL module usage.';
CREATE INDEX IF NOT EXISTS "IX_FISICOLOGICO_FechaAjuste" ON dbo."FISICOLOGICO" ("FechaAjuste");
CREATE INDEX IF NOT EXISTS "IX_FISICOLOGICO_CodigoBarra" ON dbo."FISICOLOGICO" ("CodigoBarra");

CREATE TABLE IF NOT EXISTS dbo."TOMAFISICA1" (
  "NumeroPagina" integer PRIMARY KEY,
  "Fecha" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "Observacion" varchar(500) NOT NULL DEFAULT '',
  "Usuario" varchar(15) NOT NULL DEFAULT 'INVE',
  "Status" smallint NOT NULL DEFAULT 0
);
COMMENT ON TABLE dbo."TOMAFISICA1" IS 'Inferred compatibility table. Columns reconstructed from SQL module usage.';

CREATE TABLE IF NOT EXISTS dbo."MOVTOMAFISICA1" (
  "NumeroPagina" integer NOT NULL,
  "Item" integer NOT NULL,
  "CodigoBarra" varchar(15) NOT NULL,
  "Cantidad" numeric(24,4) NOT NULL DEFAULT 0,
  "Fecha" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_MOVTOMAFISICA1_INFERRED" PRIMARY KEY ("NumeroPagina", "Item"),
  CONSTRAINT "FK_MOVTOMAFISICA1_TOMAFISICA1_INFERRED" FOREIGN KEY ("NumeroPagina") REFERENCES dbo."TOMAFISICA1"("NumeroPagina") ON DELETE CASCADE,
  CONSTRAINT "FK_MOVTOMAFISICA1_INVENTARIO_INFERRED" FOREIGN KEY ("CodigoBarra") REFERENCES dbo."INVENTARIO"("CodigoBarra") ON UPDATE CASCADE
);
COMMENT ON TABLE dbo."MOVTOMAFISICA1" IS 'Inferred compatibility table. Columns reconstructed from SQL module usage.';
CREATE UNIQUE INDEX IF NOT EXISTS "UX_MOVTOMAFISICA1_NumeroPagina_CodigoBarra" ON dbo."MOVTOMAFISICA1" ("NumeroPagina", "CodigoBarra");

CREATE TABLE IF NOT EXISTS dbo."MOVTOMAFISICA2" (
  "NumeroPagina" integer NOT NULL,
  "Item" integer NOT NULL,
  "CodigoBarra" varchar(15) NOT NULL,
  "Cantidad" numeric(24,4) NOT NULL DEFAULT 0,
  "Fecha" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_MOVTOMAFISICA2_INFERRED" PRIMARY KEY ("NumeroPagina", "Item")
);
COMMENT ON TABLE dbo."MOVTOMAFISICA2" IS 'Inferred compatibility table. Columns reconstructed from SQL module usage.';
CREATE UNIQUE INDEX IF NOT EXISTS "UX_MOVTOMAFISICA2_NumeroPagina_CodigoBarra" ON dbo."MOVTOMAFISICA2" ("NumeroPagina", "CodigoBarra");

CREATE TABLE IF NOT EXISTS dbo."TABLA_VALORES" (
  "IdTabla" varchar(100) NOT NULL,
  "Codigo" integer NOT NULL DEFAULT 0,
  "Descripcion" varchar(500) NOT NULL DEFAULT ''
);
COMMENT ON TABLE dbo."TABLA_VALORES" IS 'Inferred compatibility table. Columns reconstructed from SQL module usage.';
CREATE UNIQUE INDEX IF NOT EXISTS "UX_TABLA_VALORES_IdTabla_Codigo" ON dbo."TABLA_VALORES" ("IdTabla", "Codigo");

CREATE TABLE IF NOT EXISTS dbo."DISPOSITIVOGRUPO" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Nombre" varchar(500) NOT NULL
);
COMMENT ON TABLE dbo."DISPOSITIVOGRUPO" IS 'Inferred compatibility table. Columns reconstructed from SQL module usage.';

CREATE TABLE IF NOT EXISTS dbo."DISPOSITIVOSMARCAJE" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Modelo" varchar(500) NOT NULL,
  "Marca" varchar(500) NOT NULL,
  "Tipo" varchar(500) NOT NULL,
  "Imagen" bytea,
  "IdGrupo" integer
);
COMMENT ON TABLE dbo."DISPOSITIVOSMARCAJE" IS 'Inferred compatibility table. Columns reconstructed from SQL module usage.';

CREATE TABLE IF NOT EXISTS dbo."CONFIGURACIONMARCAJE" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IdDispositivo" integer NOT NULL,
  "Dispositivo" varchar(500) NOT NULL,
  "FechaRegistro" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "FK_CONFIGURACIONMARCAJE_DISPOSITIVOSMARCAJE_INFERRED" FOREIGN KEY ("IdDispositivo") REFERENCES dbo."DISPOSITIVOSMARCAJE"("Id") ON UPDATE CASCADE
);
COMMENT ON TABLE dbo."CONFIGURACIONMARCAJE" IS 'Inferred compatibility table. Columns reconstructed from SQL module usage.';

CREATE TABLE IF NOT EXISTS dbo."CONTROLACCESO" (
  "Numero" integer PRIMARY KEY,
  "Cedula" varchar(15) NOT NULL,
  "Fecha" date NOT NULL,
  "HoraEntrada" timestamp(0) without time zone,
  "HoraSalida" timestamp(0) without time zone,
  CONSTRAINT "FK_CONTROLACCESO_TRABAJADORES_INFERRED" FOREIGN KEY ("Cedula") REFERENCES dbo."TRABAJADORES"("Cedula") ON UPDATE CASCADE
);
COMMENT ON TABLE dbo."CONTROLACCESO" IS 'Inferred compatibility table. Columns reconstructed from SQL module usage.';
CREATE INDEX IF NOT EXISTS "IX_CONTROLACCESO_Cedula_Fecha" ON dbo."CONTROLACCESO" ("Cedula", "Fecha");

CREATE TABLE IF NOT EXISTS dbo."PATRON" (
  "IdPatron" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IdPersonal" varchar(15) NOT NULL,
  "IdMano" smallint NOT NULL,
  "IdDedo" smallint NOT NULL,
  "Patron" bytea NOT NULL,
  "FechaRegistro" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "IndEstatus" smallint NOT NULL DEFAULT 1,
  CONSTRAINT "FK_PATRON_TRABAJADORES_INFERRED" FOREIGN KEY ("IdPersonal") REFERENCES dbo."TRABAJADORES"("Cedula") ON UPDATE CASCADE
);
COMMENT ON TABLE dbo."PATRON" IS 'Inferred compatibility table. Columns reconstructed from SQL module usage.';

CREATE TABLE IF NOT EXISTS dbo."DETALLECONTROLACCESO" (
  "IdDetalleControlAcceso" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IdPersonal" varchar(15) NOT NULL,
  "IdPatron" bigint,
  "Fecha" timestamp(0) without time zone NOT NULL,
  "IndTipoMarcaje" smallint NOT NULL,
  "IndUsoCarnet" smallint NOT NULL,
  CONSTRAINT "FK_DETALLECONTROLACCESO_TRABAJADORES_INFERRED" FOREIGN KEY ("IdPersonal") REFERENCES dbo."TRABAJADORES"("Cedula") ON UPDATE CASCADE,
  CONSTRAINT "FK_DETALLECONTROLACCESO_PATRON_INFERRED" FOREIGN KEY ("IdPatron") REFERENCES dbo."PATRON"("IdPatron") ON UPDATE CASCADE
);
COMMENT ON TABLE dbo."DETALLECONTROLACCESO" IS 'Inferred compatibility table. Columns reconstructed from SQL module usage.';
CREATE INDEX IF NOT EXISTS "IX_DETALLECONTROLACCESO_IdPersonal_Fecha" ON dbo."DETALLECONTROLACCESO" ("IdPersonal", "Fecha");

CREATE TABLE IF NOT EXISTS dbo."CODIGOS_RECARGOS" (
  "CodigoBarra" varchar(15) PRIMARY KEY
);
COMMENT ON TABLE dbo."CODIGOS_RECARGOS" IS 'Inferred compatibility table. Columns reconstructed from SQL module usage.';

CREATE TABLE IF NOT EXISTS dbo."GRUPO_REGLAS" (
  "ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IDGrupoRegla" integer NOT NULL,
  "CodigoBarra" varchar(18) NOT NULL,
  "EsReferencia" smallint NOT NULL DEFAULT 0,
  "EsExcepcion" smallint NOT NULL DEFAULT 0
);
COMMENT ON TABLE dbo."GRUPO_REGLAS" IS 'Inferred compatibility table. Columns reconstructed from SQL module usage.';
CREATE INDEX IF NOT EXISTS "IX_GRUPO_REGLAS_Grupo" ON dbo."GRUPO_REGLAS" ("IDGrupoRegla");
CREATE INDEX IF NOT EXISTS "IX_GRUPO_REGLAS_CodigoBarra" ON dbo."GRUPO_REGLAS" ("CodigoBarra");

CREATE TABLE IF NOT EXISTS dbo."REGLAS" (
  "ID" bigint PRIMARY KEY,
  "Descripcion" varchar(250) NOT NULL,
  "Imprimir" varchar(10) NOT NULL,
  "Lleve" integer NOT NULL,
  "Pague" integer NOT NULL,
  "PorcDescuento" numeric(7,4),
  "ProductosActivan" bigint NOT NULL,
  "ProductosAfectados" bigint NOT NULL,
  "FechaInicio" date NOT NULL,
  "FechaFin" date NOT NULL,
  "HoraInicio" time without time zone NOT NULL,
  "HoraFin" time without time zone NOT NULL,
  "Lunes" smallint NOT NULL DEFAULT 0,
  "Martes" smallint NOT NULL DEFAULT 0,
  "Miercoles" smallint NOT NULL DEFAULT 0,
  "Jueves" smallint NOT NULL DEFAULT 0,
  "Viernes" smallint NOT NULL DEFAULT 0,
  "Sabado" smallint NOT NULL DEFAULT 0,
  "Domingo" smallint NOT NULL DEFAULT 0,
  "Prioridad" bigint NOT NULL DEFAULT 0,
  "Activa" smallint NOT NULL DEFAULT 0,
  "FechaCreacion" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "Precio" numeric(10,2) NOT NULL DEFAULT 0,
  "Tipo" integer NOT NULL DEFAULT 0
);
COMMENT ON TABLE dbo."REGLAS" IS 'Inferred compatibility table. Columns reconstructed from SQL module usage.';

CREATE TABLE IF NOT EXISTS dbo."REFERENCIAS_MAYORISTAS" (
  "Codigo" varchar(18) NOT NULL,
  "EsExcepcion" smallint NOT NULL DEFAULT 0
);
COMMENT ON TABLE dbo."REFERENCIAS_MAYORISTAS" IS 'Inferred compatibility table. Columns reconstructed from SQL module usage.';

CREATE TABLE IF NOT EXISTS dbo."DESCUENTO_MAYORISTA" (
  "MontoMinimo" numeric(24,2) NOT NULL,
  "PorcentajeDescuento" numeric(5,2) NOT NULL DEFAULT 0
);
COMMENT ON TABLE dbo."DESCUENTO_MAYORISTA" IS 'Inferred compatibility table. Columns reconstructed from SQL module usage.';

CREATE TABLE IF NOT EXISTS dbo."SALDODIARIO" (
  "Fecha" date NOT NULL,
  "CodigoBarra" varchar(15) NOT NULL,
  "TotalDevVentasCant" numeric(24,4) NOT NULL DEFAULT 0,
  "TotalTransferenciasRecCant" numeric(24,4) NOT NULL DEFAULT 0,
  "TotalDevTransferenciasCant" numeric(24,4) NOT NULL DEFAULT 0,
  "TotalComprasCant" numeric(24,4) NOT NULL DEFAULT 0,
  "TotalAjustesPositivosCant" numeric(24,4) NOT NULL DEFAULT 0,
  "TotalAFSPositivosCant" numeric(24,4) NOT NULL DEFAULT 0,
  "TotalVentasCant" numeric(24,4) NOT NULL DEFAULT 0,
  "TotalDevTransferenciasRecCant" numeric(24,4) NOT NULL DEFAULT 0,
  "TotalTransferenciasCant" numeric(24,4) NOT NULL DEFAULT 0,
  "TotalDevComprasCant" numeric(24,4) NOT NULL DEFAULT 0,
  "TotalAjustesNegativosCant" numeric(24,4) NOT NULL DEFAULT 0,
  "TotalAFSNegativosCant" numeric(24,4) NOT NULL DEFAULT 0
);
COMMENT ON TABLE dbo."SALDODIARIO" IS 'Inferred compatibility table. Columns reconstructed from SQL module usage.';
CREATE INDEX IF NOT EXISTS "IX_SALDODIARIO_Fecha_CodigoBarra" ON dbo."SALDODIARIO" ("Fecha", "CodigoBarra");

-- -----------------------------------------------------------------------------
-- Scalar and table functions
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION dbo."ExtraerEnteros"(p_string varchar)
RETURNS varchar(1000)
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT left(regexp_replace(coalesce(p_string, ''), '[^0-9]', '', 'g'), 1000)::varchar(1000);
$$;

CREATE OR REPLACE FUNCTION dbo."UltimaTasaCambio"()
RETURNS numeric(18,4)
LANGUAGE sql
STABLE
AS $$
  SELECT coalesce((SELECT "Valor"::numeric(18,4) FROM dbo."TASA_CAMBIO" ORDER BY "Fecha" DESC LIMIT 1), 1::numeric(18,4));
$$;

CREATE OR REPLACE FUNCTION dbo."fSALDODIARIO_InventarioDiario"(p_fecha_referencia varchar)
RETURNS TABLE("CodigoBarra" varchar(15), "Existencia" numeric(24,4))
LANGUAGE sql
STABLE
AS $$
  SELECT i."CodigoBarra", coalesce(i."Existencia", 0)::numeric(24,4)
  FROM dbo."INVENTARIO" i;
$$;

CREATE OR REPLACE FUNCTION dbo."fntPrendasGrupoRegla"(p_idgrupo integer)
RETURNS TABLE("CodigoBarra" varchar(15), "IDGrupoRegla" integer)
LANGUAGE sql
STABLE
AS $$
  SELECT gr."CodigoBarra"::varchar(15), gr."IDGrupoRegla"::integer
  FROM dbo."GRUPO_REGLAS" gr
  WHERE gr."IDGrupoRegla" = p_idgrupo
    AND gr."EsReferencia" = 0
    AND gr."EsExcepcion" = 0

  UNION

  SELECT inv."CodigoBarra"::varchar(15), gr."IDGrupoRegla"::integer
  FROM dbo."GRUPO_REGLAS" gr
  INNER JOIN dbo."INVENTARIO" inv
    ON trim(inv."Referencia") || trim(inv."CodigoMarca") = gr."CodigoBarra"
   AND gr."EsReferencia" = 1
   AND gr."EsExcepcion" = 0
  WHERE gr."IDGrupoRegla" = p_idgrupo

  UNION

  SELECT i."CodigoBarra"::varchar(15), p_idgrupo::integer
  FROM dbo."INVENTARIO" i
  LEFT JOIN (
    SELECT i2."CodigoBarra"
    FROM dbo."INVENTARIO" i2
    INNER JOIN dbo."GRUPO_REGLAS" gr2
      ON gr2."CodigoBarra" = trim(i2."Referencia") || trim(i2."CodigoMarca")
     AND gr2."IDGrupoRegla" = p_idgrupo
     AND gr2."EsReferencia" = 1
     AND gr2."EsExcepcion" = 1

    UNION

    SELECT gr3."CodigoBarra"
    FROM dbo."GRUPO_REGLAS" gr3
    WHERE gr3."IDGrupoRegla" = p_idgrupo
      AND gr3."EsReferencia" = 0
      AND gr3."EsExcepcion" = 1
  ) res
    ON i."CodigoBarra" = res."CodigoBarra"
  WHERE res."CodigoBarra" IS NULL
    AND EXISTS (
      SELECT 1
      FROM dbo."GRUPO_REGLAS" gr4
      WHERE gr4."IDGrupoRegla" = p_idgrupo
        AND gr4."EsExcepcion" = 1
    )
    AND NOT EXISTS (
      SELECT 1
      FROM dbo."CODIGOS_RECARGOS" cr
      WHERE cr."CodigoBarra" = i."CodigoBarra"
    )

  UNION

  SELECT i."CodigoBarra"::varchar(15), p_idgrupo::integer
  FROM dbo."INVENTARIO" i
  WHERE EXISTS (
      SELECT 1
      FROM dbo."GRUPO_REGLAS" gr5
      WHERE gr5."CodigoBarra" = '+++'
        AND gr5."IDGrupoRegla" = p_idgrupo
    )
    AND NOT EXISTS (
      SELECT 1
      FROM dbo."CODIGOS_RECARGOS" cr
      WHERE cr."CodigoBarra" = i."CodigoBarra"
    );
$$;

CREATE OR REPLACE FUNCTION dbo."fntReglasPrenda"(p_codigobarra varchar(15), p_activa smallint)
RETURNS TABLE(
  "ID" bigint,
  "Descripcion" varchar(250),
  "Imprimir" varchar(10),
  "Lleve" integer,
  "Pague" integer,
  "PorcDescuento" numeric(7,4),
  "ProductosActivan" bigint,
  "ProductosAfectados" bigint,
  "FechaInicio" date,
  "FechaFin" date,
  "HoraInicio" time without time zone,
  "HoraFin" time without time zone,
  "Lunes" smallint,
  "Martes" smallint,
  "Miercoles" smallint,
  "Jueves" smallint,
  "Viernes" smallint,
  "Sabado" smallint,
  "Domingo" smallint,
  "Prioridad" bigint,
  "Activa" smallint,
  "FechaCreacion" timestamp(0) without time zone,
  "Precio" numeric(10,2),
  "Tipo" integer
)
LANGUAGE sql
STABLE
AS $$
  SELECT
    r."ID",
    r."Descripcion",
    r."Imprimir",
    r."Lleve",
    r."Pague",
    r."PorcDescuento",
    r."ProductosActivan",
    r."ProductosAfectados",
    r."FechaInicio",
    r."FechaFin",
    r."HoraInicio",
    r."HoraFin",
    r."Lunes",
    r."Martes",
    r."Miercoles",
    r."Jueves",
    r."Viernes",
    r."Sabado",
    r."Domingo",
    r."Prioridad",
    r."Activa",
    r."FechaCreacion",
    r."Precio",
    r."Tipo"
  FROM dbo."REGLAS" r
  INNER JOIN (
    SELECT gr."IDGrupoRegla"
    FROM dbo."GRUPO_REGLAS" gr
    WHERE gr."CodigoBarra" = p_codigobarra
      AND gr."EsReferencia" = 0
      AND gr."EsExcepcion" = 0
    GROUP BY gr."IDGrupoRegla"

    UNION

    SELECT gr."IDGrupoRegla"
    FROM dbo."GRUPO_REGLAS" gr
    INNER JOIN dbo."INVENTARIO" inv
      ON trim(inv."Referencia") || trim(inv."CodigoMarca") = gr."CodigoBarra"
     AND inv."CodigoBarra" = p_codigobarra
    WHERE gr."EsReferencia" = 1
      AND gr."EsExcepcion" = 0
    GROUP BY gr."IDGrupoRegla"

    UNION

    SELECT gr."IDGrupoRegla"
    FROM dbo."INVENTARIO" i
    INNER JOIN dbo."GRUPO_REGLAS" gr
      ON gr."CodigoBarra" = trim(i."Referencia") || trim(i."CodigoMarca")
     AND gr."EsReferencia" = 1
     AND gr."EsExcepcion" = 1
    WHERE gr."CodigoBarra" NOT IN (
        SELECT trim(i2."Referencia") || trim(i2."CodigoMarca")
        FROM dbo."INVENTARIO" i2
        WHERE i2."CodigoBarra" = p_codigobarra
    )
      AND EXISTS (
        SELECT 1
        FROM dbo."INVENTARIO" i3
        LEFT JOIN dbo."GRUPO_REGLAS" grx
          ON grx."CodigoBarra" = trim(i3."Referencia") || trim(i3."CodigoMarca")
         AND grx."EsReferencia" = 1
         AND grx."EsExcepcion" = 1
         AND grx."CodigoBarra" NOT IN (
            SELECT trim(i4."Referencia") || trim(i4."CodigoMarca")
            FROM dbo."INVENTARIO" i4
            WHERE i4."CodigoBarra" = p_codigobarra
         )
        WHERE grx."ID" IS NULL
          AND i3."CodigoBarra" = p_codigobarra
      )
    GROUP BY gr."IDGrupoRegla"

    UNION

    SELECT gr."IDGrupoRegla"
    FROM dbo."INVENTARIO" i
    INNER JOIN dbo."GRUPO_REGLAS" gr
      ON gr."CodigoBarra" = i."CodigoBarra"
     AND gr."EsReferencia" = 0
     AND gr."EsExcepcion" = 1
    WHERE gr."CodigoBarra" <> p_codigobarra
      AND EXISTS (
        SELECT 1
        FROM dbo."INVENTARIO" i5
        LEFT JOIN dbo."GRUPO_REGLAS" gry
          ON gry."CodigoBarra" = i5."CodigoBarra"
         AND gry."EsReferencia" = 0
         AND gry."EsExcepcion" = 1
         AND gry."CodigoBarra" <> p_codigobarra
        WHERE gry."ID" IS NULL
          AND i5."CodigoBarra" = p_codigobarra
      )
    GROUP BY gr."IDGrupoRegla"

    UNION

    SELECT gr."IDGrupoRegla"
    FROM dbo."GRUPO_REGLAS" gr
    WHERE gr."CodigoBarra" = '+++'
    GROUP BY gr."IDGrupoRegla"
  ) res
    ON r."ProductosActivan" = res."IDGrupoRegla"
  WHERE r."Activa" = p_activa
    AND CURRENT_DATE BETWEEN r."FechaInicio" AND r."FechaFin"
    AND LOCALTIME >= r."HoraInicio"
    AND LOCALTIME <= r."HoraFin";
$$;

CREATE OR REPLACE FUNCTION dbo."fn_diagramobjects"()
RETURNS integer
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
  installed integer := 0;
BEGIN
  IF EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname = 'dbo' AND p.proname = 'sp_upgraddiagrams') THEN
    installed := installed + 1;
  END IF;
  IF to_regclass('dbo.sysdiagrams') IS NOT NULL THEN
    installed := installed + 2;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname = 'dbo' AND p.proname = 'sp_helpdiagrams') THEN
    installed := installed + 4;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname = 'dbo' AND p.proname = 'sp_helpdiagramdefinition') THEN
    installed := installed + 8;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname = 'dbo' AND p.proname = 'sp_creatediagram') THEN
    installed := installed + 16;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname = 'dbo' AND p.proname = 'sp_renamediagram') THEN
    installed := installed + 32;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname = 'dbo' AND p.proname = 'sp_alterdiagram') THEN
    installed := installed + 64;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname = 'dbo' AND p.proname = 'sp_dropdiagram') THEN
    installed := installed + 128;
  END IF;
  RETURN installed;
END;
$$;

-- -----------------------------------------------------------------------------
-- Views
-- -----------------------------------------------------------------------------

CREATE OR REPLACE VIEW dbo."VW_AJUSTESNEGATIVOS" AS
WITH "AJUSTESNEGATIVOS_CTE" AS (
  SELECT
    a."Fecha",
    m."CodigoBarra",
    sum(m."Cantidad") AS "UND_AJUSTESNEGATIVOS",
    sum(m."Cantidad" * m."Costo") AS "COSTO_AJUSTESNEGATIVOS"
  FROM dbo."AJUSTES" a
  INNER JOIN dbo."MOVAJUSTES" m ON a."Numero" = m."Numero"
  WHERE a."Status" <> 0 AND a."Signo" = -1
  GROUP BY a."Fecha", m."CodigoBarra"
)
SELECT "Fecha", "CodigoBarra", "UND_AJUSTESNEGATIVOS", "COSTO_AJUSTESNEGATIVOS"
FROM "AJUSTESNEGATIVOS_CTE";

CREATE OR REPLACE VIEW dbo."VW_AJUSTESPOSITIVOS" AS
WITH "AJUSTESPOSITIVOS_CTE" AS (
  SELECT
    a."Fecha",
    m."CodigoBarra",
    sum(m."Cantidad") AS "UND_AJUSTESPOSITIVOS",
    sum(m."Cantidad" * m."Costo") AS "COSTO_AJUSTEPOSITIVO"
  FROM dbo."AJUSTES" a
  INNER JOIN dbo."MOVAJUSTES" m ON a."Numero" = m."Numero"
  WHERE a."Status" <> 0 AND a."Signo" = 1
  GROUP BY a."Fecha", m."CodigoBarra"
)
SELECT "Fecha", "CodigoBarra", "UND_AJUSTESPOSITIVOS", "COSTO_AJUSTEPOSITIVO"
FROM "AJUSTESPOSITIVOS_CTE";

CREATE OR REPLACE VIEW dbo."VW_COMPRAS_REFERENCIA_MARCA" AS
SELECT DISTINCT
  xxx."Documento",
  xxx."Fecha_Factura",
  xxx."PrecioProrrateado",
  xxx."Nombre",
  xxx."Referencia",
  xxx."CodigoMarca"
FROM (
  SELECT DISTINCT
    max(c."Documento") AS "Documento",
    max(c."FechaFactura") AS "Fecha_Factura",
    max(mc."PrecioProrrateado") AS "PrecioProrrateado",
    pr."Nombre",
    i."Referencia",
    i."CodigoMarca"
  FROM dbo."COMPRAS" c
  INNER JOIN dbo."MOVCOMPRAS" mc ON mc."Documento" = c."Documento" AND c."Proveedor" = mc."Proveedor"
  INNER JOIN dbo."PROVEEDORES" pr ON pr."Codigo" = mc."Proveedor"
  INNER JOIN dbo."INVENTARIO" i ON i."CodigoBarra" = mc."CodigoBarra"
  GROUP BY pr."Nombre", i."Referencia", i."CodigoMarca"
) xxx
INNER JOIN (
  SELECT DISTINCT
    max(c."FechaFactura") AS "Fecha_Factura",
    i."Referencia",
    i."CodigoMarca"
  FROM dbo."COMPRAS" c
  INNER JOIN dbo."MOVCOMPRAS" mc ON mc."Documento" = c."Documento" AND c."Proveedor" = mc."Proveedor"
  INNER JOIN dbo."PROVEEDORES" pr ON pr."Codigo" = mc."Proveedor"
  INNER JOIN dbo."INVENTARIO" i ON i."CodigoBarra" = mc."CodigoBarra"
  GROUP BY i."Referencia", i."CodigoMarca"
) aa ON aa."Fecha_Factura" = xxx."Fecha_Factura"
    AND xxx."Referencia" = aa."Referencia"
    AND xxx."CodigoMarca" = aa."CodigoMarca";

CREATE OR REPLACE VIEW dbo."VW_COMPRASXPROVEEDOR" AS
WITH "COMPRAS_CTE" AS (
  SELECT
    c."Fecha",
    c."Proveedor",
    mc."CodigoBarra",
    sum(mc."Cantidad") AS "UND_COMPRADAS",
    sum(mc."Cantidad" * mc."PrecioFactura") AS "COSTO_COMPRA"
  FROM dbo."COMPRAS" c
  INNER JOIN dbo."MOVCOMPRAS" mc ON c."Proveedor" = mc."Proveedor" AND c."Documento" = mc."Documento"
  WHERE c."Status" <> 0
  GROUP BY c."Fecha", c."Proveedor", mc."CodigoBarra"
)
SELECT "Fecha", "Proveedor", "CodigoBarra", "UND_COMPRADAS", "COSTO_COMPRA"
FROM "COMPRAS_CTE";

CREATE OR REPLACE VIEW dbo."VW_ConfiguracionMarcaje" AS
SELECT "Id", "IdDispositivo", "Dispositivo", "FechaRegistro"
FROM dbo."CONFIGURACIONMARCAJE";

CREATE OR REPLACE VIEW dbo."VW_DEVCOMPRASXPROVEEDOR" AS
WITH "DEVCOMPRAS_CTE" AS (
  SELECT
    d."Fecha",
    m."CodigoBarra",
    sum(m."Cantidad") AS "UND_DEVCOMPRADAS",
    sum(m."Cantidad" * m."Precio") AS "COSTO_DEVCOMPRA"
  FROM dbo."DEVCOMPRAS" d
  INNER JOIN dbo."MOVDEVCOMPRAS" m ON d."Numero" = m."Numero"
  WHERE d."Status" <> 0
  GROUP BY d."Fecha", d."Proveedor", m."CodigoBarra"
)
SELECT "Fecha", "CodigoBarra", "UND_DEVCOMPRADAS", "COSTO_DEVCOMPRA"
FROM "DEVCOMPRAS_CTE";

CREATE OR REPLACE VIEW dbo."VW_DEVTRANSFERENCIAS" AS
WITH "DEVTRANSFERENCIAS_CTE" AS (
  SELECT
    d."Fecha",
    d."CodigoRecibe",
    m."CodigoBarra",
    sum(m."Cantidad") AS "UND_DEVTRANSFERIDAS",
    sum(m."Cantidad" * m."Valor") AS "COSTO_DEVTRANSFERENCIA"
  FROM dbo."DEVTRANSFERENCIAS" d
  INNER JOIN dbo."MOVDEVTRANSFERENCIAS" m ON d."Numero" = m."Numero"
  WHERE d."Status" <> 0
  GROUP BY d."Fecha", d."CodigoRecibe", m."CodigoBarra"
)
SELECT "Fecha", "CodigoRecibe", "CodigoBarra", "UND_DEVTRANSFERIDAS", "COSTO_DEVTRANSFERENCIA"
FROM "DEVTRANSFERENCIAS_CTE";

CREATE OR REPLACE VIEW dbo."VW_DispositivoGrupo" AS
SELECT "Id", "Nombre"
FROM dbo."DISPOSITIVOGRUPO";

CREATE OR REPLACE VIEW dbo."VW_DispositivoMarcaje" AS
SELECT "Id", "Modelo", "Marca", "Tipo", "Imagen", "IdGrupo"
FROM dbo."DISPOSITIVOSMARCAJE";

CREATE OR REPLACE VIEW dbo."VW_DIVISION" AS
SELECT "Codigo" AS "CodigoDivision", "Nombre" AS "Division"
FROM dbo."CATEGORIAS"
WHERE length("Codigo") = 2;

CREATE OR REPLACE VIEW dbo."VW_FAMILIA" AS
SELECT
  "Codigo" AS "CodigoFamilia",
  "Nombre" AS "Familia",
  substring("Codigo" FROM 1 FOR 2) AS "CodigoDivision",
  substring("Codigo" FROM 1 FOR 4) AS "CodigoSeccion"
FROM dbo."CATEGORIAS"
WHERE length("Codigo") = 6;

CREATE OR REPLACE VIEW dbo."VW_SECCION" AS
SELECT
  "Codigo" AS "CodigoSeccion",
  "Nombre" AS "Seccion",
  substring("Codigo" FROM 1 FOR 2) AS "CodigoDivision"
FROM dbo."CATEGORIAS"
WHERE length("Codigo") = 4;

CREATE OR REPLACE VIEW dbo."VW_TRANSFERENCIAS" AS
WITH "TRANSFERENCIAS_CTE" AS (
  SELECT
    t."Fecha",
    t."CodigoRecibe",
    m."CodigoBarra",
    sum(m."Cantidad") AS "UND_TRANSFERIDAS",
    sum(m."Cantidad" * m."Valor") AS "COSTO_TRANSFERENCIA"
  FROM dbo."TRANSFERENCIAS" t
  INNER JOIN dbo."MOVTRANSFERENCIAS" m ON t."Numero" = m."Numero"
  WHERE t."Status" <> 0
  GROUP BY t."Fecha", t."CodigoRecibe", m."CodigoBarra"
)
SELECT "Fecha", "CodigoRecibe", "CodigoBarra", "UND_TRANSFERIDAS", "COSTO_TRANSFERENCIA"
FROM "TRANSFERENCIAS_CTE";

-- -----------------------------------------------------------------------------
-- Query and business routines translated to PostgreSQL
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION dbo."ApiBuscarTest"()
RETURNS TABLE("Nombre" text)
LANGUAGE sql
STABLE
AS $$
  SELECT p."Nombre"::text
  FROM dbo."PARAMETROS" p;
$$;

CREATE OR REPLACE PROCEDURE dbo."ApiBuscarTomaFisica"(
  p_codigobarra varchar(20),
  p_numeropagina integer,
  p_observacion varchar(500)
)
LANGUAGE plpgsql
AS $$
DECLARE
  v_existearticulo integer := 0;
  v_existearticulotoma integer := 0;
  v_existetoma integer := 0;
  v_id integer := 0;
BEGIN
  SELECT coalesce(count(*), 0) INTO v_existearticulo
  FROM dbo."INVENTARIO"
  WHERE "CodigoBarra" = p_codigobarra;

  IF v_existearticulo > 0 THEN
    SELECT coalesce(count("NumeroPagina"), 0) INTO v_existetoma
    FROM dbo."TOMAFISICA1"
    WHERE "NumeroPagina" = p_numeropagina;

    IF v_existetoma > 0 THEN
      UPDATE dbo."TOMAFISICA1"
      SET "Observacion" = p_observacion
      WHERE "NumeroPagina" = p_numeropagina;
    ELSE
      INSERT INTO dbo."TOMAFISICA1" ("NumeroPagina", "Fecha", "Observacion", "Usuario", "Status")
      VALUES (p_numeropagina, CURRENT_TIMESTAMP, p_observacion, 'INVE', 1);
    END IF;

    SELECT coalesce((SELECT "NumeroPagina" FROM dbo."MOVTOMAFISICA1" WHERE "CodigoBarra" = p_codigobarra LIMIT 1), 0)
      INTO v_existearticulotoma;

    IF v_existearticulotoma > 0 THEN
      UPDATE dbo."MOVTOMAFISICA1"
      SET "Cantidad" = "Cantidad" + 1
      WHERE "CodigoBarra" = p_codigobarra
        AND "NumeroPagina" = p_numeropagina;
    ELSE
      SELECT coalesce(max("Item"), 0) + 1 INTO v_id
      FROM dbo."MOVTOMAFISICA1"
      WHERE "NumeroPagina" = p_numeropagina;

      INSERT INTO dbo."MOVTOMAFISICA1" ("NumeroPagina", "Item", "CodigoBarra", "Cantidad", "Fecha")
      VALUES (p_numeropagina, v_id, p_codigobarra, 1, CURRENT_TIMESTAMP);
    END IF;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION dbo."ApiBuscarTomaFisicaDetalle"(p_numeropagina integer)
RETURNS TABLE(
  "NumeroPagina" integer,
  "Nombre" text,
  "Item" integer,
  "CodigoBarra" varchar(15),
  "Cantidad" numeric(24,4)
)
LANGUAGE sql
STABLE
AS $$
  SELECT m."NumeroPagina", i."Nombre"::text, m."Item", m."CodigoBarra", m."Cantidad"
  FROM dbo."MOVTOMAFISICA1" m
  INNER JOIN dbo."INVENTARIO" i ON m."CodigoBarra" = i."CodigoBarra"
  WHERE m."NumeroPagina" = p_numeropagina
  ORDER BY m."Item" DESC;
$$;

CREATE OR REPLACE FUNCTION dbo."ApiBuscarTomaFisicaMae"()
RETURNS TABLE(
  "NumeroPagina" integer,
  "Fecha" timestamp(0) without time zone,
  "Observacion" text
)
LANGUAGE sql
STABLE
AS $$
  SELECT t."NumeroPagina", t."Fecha", t."Observacion"::text
  FROM dbo."TOMAFISICA1" t
  WHERE t."Usuario" = 'INVE' AND t."Status" = 0
  ORDER BY t."NumeroPagina" DESC, t."Fecha" DESC;
$$;

CREATE OR REPLACE FUNCTION dbo."ApiBuscarTomaFisicaPost"(p_numeropagina integer, p_codigobarra varchar(20))
RETURNS TABLE(
  "Cantidad" numeric(24,4),
  "Nombre" text
)
LANGUAGE sql
STABLE
AS $$
  SELECT m."Cantidad", i."Nombre"::text
  FROM dbo."TOMAFISICA1" t
  INNER JOIN dbo."MOVTOMAFISICA1" m ON t."NumeroPagina" = m."NumeroPagina"
  INNER JOIN dbo."INVENTARIO" i ON m."CodigoBarra" = i."CodigoBarra"
  WHERE m."NumeroPagina" = p_numeropagina
    AND m."CodigoBarra" = p_codigobarra;
$$;

CREATE OR REPLACE FUNCTION dbo."ApiBuscarTomaFisicaTotal"(p_numpagina integer)
RETURNS TABLE("Cantidad" numeric(24,4))
LANGUAGE sql
STABLE
AS $$
  SELECT coalesce(sum(m."Cantidad"), 0)::numeric(24,4) AS "Cantidad"
  FROM dbo."MOVTOMAFISICA1" m
  WHERE m."NumeroPagina" = p_numpagina;
$$;

CREATE OR REPLACE FUNCTION dbo."ApiBuscarValores"()
RETURNS TABLE("IdTabla" varchar(100), "Descripcion" varchar(500))
LANGUAGE plpgsql
AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM dbo."TABLA_VALORES" WHERE "IdTabla" = 'ValorLectorScaner'
  ) THEN
    INSERT INTO dbo."TABLA_VALORES" ("IdTabla", "Codigo", "Descripcion")
    VALUES ('ValorLectorScaner', 99, 'FALSE');
  END IF;

  RETURN QUERY
  SELECT v."IdTabla", v."Descripcion"
  FROM dbo."TABLA_VALORES" v
  WHERE v."IdTabla" = 'ValorLectorScaner';
END;
$$;

CREATE OR REPLACE PROCEDURE dbo."ApiProcesarToma"(
  p_codigobarra varchar(20),
  p_numeropagina integer,
  p_observacion varchar(500),
  p_cantidad integer,
  p_valor boolean
)
LANGUAGE plpgsql
AS $$
DECLARE
  v_existearticulo integer := 0;
  v_existearticulotoma integer := 0;
  v_existetoma integer := 0;
  v_id integer := 0;
BEGIN
  SELECT coalesce(count("CodigoBarra"), 0) INTO v_existearticulo
  FROM dbo."INVENTARIO"
  WHERE "CodigoBarra" = p_codigobarra;

  IF v_existearticulo > 0 THEN
    SELECT coalesce(count("NumeroPagina"), 0) INTO v_existetoma
    FROM dbo."TOMAFISICA1"
    WHERE "NumeroPagina" = p_numeropagina;

    IF v_existetoma > 0 THEN
      UPDATE dbo."TOMAFISICA1"
      SET "Observacion" = p_observacion
      WHERE "NumeroPagina" = p_numeropagina;
    ELSE
      INSERT INTO dbo."TOMAFISICA1" ("NumeroPagina", "Fecha", "Observacion", "Usuario", "Status")
      VALUES (p_numeropagina, CURRENT_TIMESTAMP, p_observacion, 'INVE', 0);
    END IF;

    SELECT coalesce(count("NumeroPagina"), 0) INTO v_existearticulotoma
    FROM dbo."MOVTOMAFISICA1"
    WHERE "CodigoBarra" = p_codigobarra
      AND "NumeroPagina" = p_numeropagina;

    IF v_existearticulotoma > 0 THEN
      IF coalesce(p_valor, FALSE) = FALSE THEN
        UPDATE dbo."MOVTOMAFISICA1"
        SET "Cantidad" = "Cantidad" + 1
        WHERE "CodigoBarra" = p_codigobarra
          AND "NumeroPagina" = p_numeropagina;
      ELSE
        UPDATE dbo."MOVTOMAFISICA1"
        SET "Cantidad" = p_cantidad
        WHERE "CodigoBarra" = p_codigobarra
          AND "NumeroPagina" = p_numeropagina;
      END IF;
    ELSE
      SELECT coalesce(max("Item"), 0) + 1 INTO v_id
      FROM dbo."MOVTOMAFISICA1"
      WHERE "NumeroPagina" = p_numeropagina;

      INSERT INTO dbo."MOVTOMAFISICA1" ("NumeroPagina", "Item", "CodigoBarra", "Cantidad", "Fecha")
      VALUES (p_numeropagina, v_id, p_codigobarra, p_cantidad, CURRENT_TIMESTAMP);
    END IF;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION dbo."BuscarCantidadMarcajeDia"(
  p_fechadia timestamp(0) without time zone,
  p_cedula varchar(10),
  p_idpersonal integer
)
RETURNS TABLE(valor bigint)
LANGUAGE plpgsql
STABLE
AS $$
BEGIN
  IF (p_cedula IS NOT NULL OR p_cedula <> '') THEN
    RETURN QUERY
    SELECT count(d."IdDetalleControlAcceso")::bigint AS valor
    FROM dbo."DETALLECONTROLACCESO" d
    INNER JOIN dbo."TRABAJADORES" t ON t."Cedula" = d."IdPersonal"
    WHERE t."Cedula" = p_cedula
      AND d."Fecha"::date = p_fechadia::date;
  ELSE
    RETURN QUERY
    SELECT count(d."IdDetalleControlAcceso")::bigint AS valor
    FROM dbo."DETALLECONTROLACCESO" d
    WHERE d."IdPersonal" = p_idpersonal::text
      AND d."Fecha"::date = p_fechadia::date;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION dbo."CONSULTAS_ENTRADASYSALIDAS"(p_mes integer, p_ano integer)
RETURNS TABLE(
  "Nombre" text,
  "Referencia" varchar(10),
  "CodigoMarca" varchar(3),
  "ExistenciasInicial" numeric(24,4),
  "Entradas" numeric(24,4),
  "Salidas" numeric(24,4),
  "ExistenciaFinal" numeric(24,4)
)
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
  v_iniciodelmes date;
  v_findelmes date;
BEGIN
  v_iniciodelmes := to_date('01/' || lpad(p_mes::text, 2, '0') || '/' || p_ano::text, 'DD/MM/YYYY');
  v_findelmes := (date_trunc('month', v_iniciodelmes + interval '1 month') - interval '1 day')::date;

  RETURN QUERY
  SELECT
    CASE
      WHEN position('T:' IN max(data."Nombre")) = 0 THEN max(data."Nombre")
      ELSE substring(max(data."Nombre") FROM 1 FOR position('T:' IN max(data."Nombre")) - 1)
    END::text AS "Nombre",
    data."Referencia",
    data."CodigoMarca",
    sum(data."ExistenciasInicial")::numeric(24,4) AS "ExistenciasInicial",
    sum(data."Entradas")::numeric(24,4) AS "Entradas",
    sum(data."Salidas")::numeric(24,4) AS "Salidas",
    sum(data."ExistenciasFinal")::numeric(24,4) AS "ExistenciaFinal"
  FROM (
    SELECT
      i."CodigoBarra",
      i."Nombre",
      i."Referencia",
      i."CodigoMarca",
      i."Talla",
      i."CodigoColor",
      coalesce(s_i."Existencia", 0)::numeric(24,4) AS "ExistenciasInicial",
      coalesce(mov."Entradas", 0)::numeric(24,4) AS "Entradas",
      coalesce(mov."Salidas", 0)::numeric(24,4) AS "Salidas",
      coalesce(s_f."Existencia", 0)::numeric(24,4) AS "ExistenciasFinal"
    FROM (
      SELECT "CodigoBarra", "Nombre", "Referencia", "CodigoMarca", "Talla", "CodigoColor"
      FROM dbo."INVENTARIO"
    ) i
    LEFT JOIN dbo."fSALDODIARIO_InventarioDiario"(to_char(v_iniciodelmes - interval '1 day', 'DD/MM/YYYY')) s_i
      ON i."CodigoBarra" = s_i."CodigoBarra"
    LEFT JOIN (
      SELECT
        s."CodigoBarra",
        sum(coalesce(s."TotalDevVentasCant", 0) + coalesce(s."TotalTransferenciasRecCant", 0) + coalesce(s."TotalDevTransferenciasCant", 0) + coalesce(s."TotalComprasCant", 0) + coalesce(s."TotalAjustesPositivosCant", 0) + coalesce(s."TotalAFSPositivosCant", 0))::numeric(24,4) AS "Entradas",
        sum(coalesce(s."TotalVentasCant", 0) + coalesce(s."TotalDevTransferenciasRecCant", 0) + coalesce(s."TotalTransferenciasCant", 0) + coalesce(s."TotalDevComprasCant", 0) + coalesce(s."TotalAjustesNegativosCant", 0) + coalesce(s."TotalAFSNegativosCant", 0))::numeric(24,4) * (-1) AS "Salidas"
      FROM dbo."SALDODIARIO" s
      WHERE s."Fecha" BETWEEN v_iniciodelmes AND v_findelmes
      GROUP BY s."CodigoBarra"
    ) mov ON i."CodigoBarra" = mov."CodigoBarra"
    LEFT JOIN dbo."fSALDODIARIO_InventarioDiario"(to_char(v_findelmes, 'DD/MM/YYYY')) s_f
      ON i."CodigoBarra" = s_f."CodigoBarra"
  ) data
  GROUP BY data."Referencia", data."CodigoMarca";
END;
$$;

CREATE OR REPLACE PROCEDURE dbo."EliminarPatron"(p_idpatron bigint)
LANGUAGE plpgsql
AS $$
BEGIN
  DELETE FROM dbo."PATRON"
  WHERE "IdPatron" = p_idpatron;
END;
$$;

CREATE OR REPLACE FUNCTION dbo."InsertarControlAcceso"(
  p_idpersonal varchar(15),
  p_fecha timestamp(0) without time zone,
  p_idpatron bigint DEFAULT NULL,
  p_fotografia bytea DEFAULT NULL,
  p_idzonahoraria varchar(50) DEFAULT NULL,
  p_indusocarnet smallint DEFAULT 0,
  p_marcajeinterdiario boolean DEFAULT FALSE
)
RETURNS smallint
LANGUAGE plpgsql
AS $$
DECLARE
  v_horaentrada timestamp(0) without time zone;
  v_horasalida timestamp(0) without time zone;
  v_fechaanterior date;
  v_numero integer := 0;
  v_numeroupdate integer := 0;
BEGIN
  SELECT coalesce(max("Numero"), 0) INTO v_numero FROM dbo."CONTROLACCESO";

  IF NOT EXISTS (
    SELECT 1
    FROM dbo."CONTROLACCESO"
    WHERE "Cedula" = p_idpersonal
      AND "Fecha" = p_fecha::date
  ) THEN
    v_fechaanterior := (p_fecha::date - 1);

    IF p_marcajeinterdiario THEN
      IF EXISTS (
        SELECT 1
        FROM dbo."CONTROLACCESO"
        WHERE "Cedula" = p_idpersonal
          AND "Fecha" = v_fechaanterior
          AND "HoraSalida" IS NULL
      ) THEN
        UPDATE dbo."CONTROLACCESO"
        SET "HoraSalida" = p_fecha
        WHERE "Cedula" = p_idpersonal
          AND "Fecha" = v_fechaanterior
          AND "Numero" = (
            SELECT c."Numero"
            FROM dbo."CONTROLACCESO" c
            WHERE c."Cedula" = p_idpersonal
              AND c."Fecha" = v_fechaanterior
            ORDER BY c."Numero" DESC
            LIMIT 1
          );
        RETURN 1;
      ELSE
        INSERT INTO dbo."CONTROLACCESO" ("Numero", "Cedula", "Fecha", "HoraEntrada")
        VALUES (v_numero + 1, p_idpersonal, p_fecha::date, p_fecha);
        RETURN 0;
      END IF;
    ELSE
      INSERT INTO dbo."CONTROLACCESO" ("Numero", "Cedula", "Fecha", "HoraEntrada")
      VALUES (v_numero + 1, p_idpersonal, p_fecha::date, p_fecha);
      RETURN 0;
    END IF;
  ELSE
    SELECT c."Numero", c."HoraEntrada", c."HoraSalida"
      INTO v_numeroupdate, v_horaentrada, v_horasalida
    FROM dbo."CONTROLACCESO" c
    WHERE c."Cedula" = p_idpersonal
      AND c."Fecha" = p_fecha::date
    ORDER BY c."Numero" DESC
    LIMIT 1;

    IF v_horasalida IS NULL THEN
      UPDATE dbo."CONTROLACCESO"
      SET "HoraSalida" = p_fecha
      WHERE "Numero" = v_numeroupdate;
      RETURN 1;
    ELSIF v_horaentrada IS NOT NULL AND v_horasalida IS NOT NULL THEN
      INSERT INTO dbo."CONTROLACCESO" ("Numero", "Cedula", "Fecha", "HoraEntrada")
      VALUES (v_numero + 1, p_idpersonal, p_fecha::date, p_fecha);
      RETURN 0;
    END IF;
  END IF;

  RETURN 0;
END;
$$;

CREATE OR REPLACE PROCEDURE dbo."InsertarControlAccesoSelectivo"(
  p_idpersonal varchar(15),
  p_fecha timestamp(0) without time zone,
  p_idpatron bigint DEFAULT NULL,
  p_fotografia bytea DEFAULT NULL,
  p_idzonahoraria varchar(50) DEFAULT NULL,
  p_indusocarnet smallint DEFAULT 0,
  p_indtipomarcaje smallint DEFAULT 0
)
LANGUAGE plpgsql
AS $$
DECLARE
  v_numero integer := 0;
BEGIN
  SELECT coalesce(max("Numero"), 0) INTO v_numero
  FROM dbo."CONTROLACCESO";

  IF p_indtipomarcaje = 0 THEN
    INSERT INTO dbo."CONTROLACCESO" ("Numero", "Cedula", "Fecha", "HoraEntrada")
    VALUES (v_numero + 1, p_idpersonal, p_fecha::date, p_fecha);
  ELSE
    INSERT INTO dbo."CONTROLACCESO" ("Numero", "Cedula", "Fecha", "HoraSalida")
    VALUES (v_numero + 1, p_idpersonal, p_fecha::date, p_fecha);
  END IF;
END;
$$;

CREATE OR REPLACE PROCEDURE dbo."InsertarDetalleControlAcceso"(
  p_idpersonal varchar(15),
  p_fecha timestamp(0) without time zone,
  p_idpatron bigint DEFAULT NULL,
  p_indtipomarcaje smallint DEFAULT 0,
  p_indusocarnet smallint DEFAULT 0
)
LANGUAGE plpgsql
AS $$
BEGIN
  INSERT INTO dbo."DETALLECONTROLACCESO" ("IdPersonal", "IdPatron", "Fecha", "IndTipoMarcaje", "IndUsoCarnet")
  VALUES (p_idpersonal, p_idpatron, p_fecha, p_indtipomarcaje, p_indusocarnet);
END;
$$;

CREATE OR REPLACE FUNCTION dbo."InsertarDispositivoMarcaje"(
  p_modelo varchar(500),
  p_marca varchar(500),
  p_tipo varchar(500),
  p_imagen bytea,
  p_idgrupo integer
)
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
  v_id integer;
BEGIN
  INSERT INTO dbo."DISPOSITIVOSMARCAJE" ("Modelo", "Marca", "Tipo", "Imagen", "IdGrupo")
  VALUES (p_modelo, p_marca, p_tipo, p_imagen, p_idgrupo)
  RETURNING "Id" INTO v_id;

  RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION dbo."InsertarDispositivoMarcajeConf"(
  p_iddispositivo integer,
  p_dispositivo varchar(500)
)
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
  v_id integer;
BEGIN
  INSERT INTO dbo."CONFIGURACIONMARCAJE" ("IdDispositivo", "Dispositivo")
  VALUES (p_iddispositivo, p_dispositivo)
  RETURNING "Id" INTO v_id;

  RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION dbo."InsertarPatron"(
  p_idpersonal varchar(15),
  p_idmano smallint,
  p_iddedo smallint,
  p_patron bytea
)
RETURNS bigint
LANGUAGE plpgsql
AS $$
DECLARE
  v_idpatron bigint;
BEGIN
  INSERT INTO dbo."PATRON" ("IdPersonal", "IdMano", "IdDedo", "Patron", "FechaRegistro", "IndEstatus")
  VALUES (p_idpersonal, p_idmano, p_iddedo, p_patron, CURRENT_TIMESTAMP, 1)
  RETURNING "IdPatron" INTO v_idpatron;

  RETURN v_idpatron;
END;
$$;

CREATE OR REPLACE FUNCTION dbo."ListarCarnetEmpleado"(p_idpersonal varchar(15) DEFAULT NULL)
RETURNS TABLE(
  "IdPersonal" integer,
  "Cedula" varchar(15),
  "Nombres" text,
  "Apellidos" text,
  "FechaIngreso" timestamp(0) without time zone,
  "FechaNacimiento" timestamp(0) without time zone,
  "Direccion" text,
  "Telefono" text,
  "Celular" text,
  "IndEstatus" smallint,
  "IndUsarCarnet" integer,
  "Fotografia" bytea,
  "IdCargo" integer,
  "NumeroCarnet" varchar(15),
  "Nacionalidad" text,
  "MarcajeInterDiario" boolean
)
LANGUAGE sql
STABLE
AS $$
  SELECT
    0 AS "IdPersonal",
    t."Cedula",
    t."Nombre"::text AS "Nombres",
    ''::text AS "Apellidos",
    t."FechaIngreso",
    t."FechaNacimiento",
    t."Direccion"::text,
    t."Telefono"::text,
    t."Celular"::text,
    t."Status" AS "IndEstatus",
    t."IndUsarCarnet",
    NULL::bytea AS "Fotografia",
    0 AS "IdCargo",
    t."Cedula" AS "NumeroCarnet",
    ''::text AS "Nacionalidad",
    t."MarcajeInterDiario"
  FROM dbo."TRABAJADORES" t
  WHERE t."Status" = 1
    AND t."Cedula" = coalesce(t."Cedula", p_idpersonal)
    AND t."IndUsarCarnet" = 1;
$$;

CREATE OR REPLACE FUNCTION dbo."ListarPatron"(
  p_idpersonal varchar(15),
  p_idmano smallint DEFAULT NULL,
  p_iddedo smallint DEFAULT NULL
)
RETURNS TABLE(
  "IdPatron" bigint,
  "IdPersonal" varchar(15),
  "IdMano" smallint,
  "IdDedo" smallint,
  "Patron" bytea
)
LANGUAGE sql
STABLE
AS $$
  SELECT p."IdPatron", p."IdPersonal", p."IdMano", p."IdDedo", p."Patron"
  FROM dbo."PATRON" p
  WHERE p."IdPersonal" = p_idpersonal
    AND p."IdMano" = coalesce(p_idmano, p."IdMano")
    AND p."IdDedo" = coalesce(p_iddedo, p."IdDedo")
    AND p."IndEstatus" = 1
  ORDER BY p."IdMano", p."IdDedo";
$$;

CREATE OR REPLACE FUNCTION dbo."ListarPatronesEmpleado"(p_idpersonal varchar(15) DEFAULT NULL)
RETURNS TABLE(
  "IdPersonal" integer,
  "Cedula" varchar(15),
  "Nombres" text,
  "Apellidos" text,
  "FechaIngreso" timestamp(0) without time zone,
  "FechaNacimiento" timestamp(0) without time zone,
  "Direccion" text,
  "Telefono" text,
  "Celular" text,
  "IndEstatus" smallint,
  "IndUsarCarnet" integer,
  "Fotografia" bytea,
  "IdCargo" integer,
  "IdPatron" bigint,
  "IdMano" smallint,
  "IdDedo" smallint,
  "Patron" bytea,
  "NumeroCarnet" text,
  "Nacionalidad" integer,
  "MarcajeInterDiario" boolean
)
LANGUAGE sql
STABLE
AS $$
  SELECT
    0 AS "IdPersonal",
    t."Cedula",
    t."Nombre"::text AS "Nombres",
    ''::text AS "Apellidos",
    t."FechaIngreso",
    t."FechaNacimiento",
    t."Direccion"::text,
    t."Telefono"::text,
    t."Celular"::text,
    t."Status" AS "IndEstatus",
    0 AS "IndUsarCarnet",
    NULL::bytea AS "Fotografia",
    0 AS "IdCargo",
    p."IdPatron",
    p."IdMano",
    p."IdDedo",
    p."Patron",
    ''::text AS "NumeroCarnet",
    0 AS "Nacionalidad",
    t."MarcajeInterDiario"
  FROM dbo."TRABAJADORES" t
  INNER JOIN dbo."PATRON" p ON t."Cedula" = p."IdPersonal"
  WHERE p."IndEstatus" = 1
    AND t."Status" = 1
    AND t."Cedula" = coalesce(t."Cedula", p_idpersonal);
$$;

CREATE OR REPLACE FUNCTION dbo."ListarPersonal"(p_idpersonal varchar(15) DEFAULT NULL)
RETURNS TABLE(
  "Cedula" varchar(15),
  "Codigo" integer,
  "Nombres" text,
  "Apellidos" text,
  "FechaIngreso" timestamp(0) without time zone,
  "FechaNacimiento" timestamp(0) without time zone,
  "Direccion" text,
  "Telefono" text,
  "Celular" text,
  "IdPersonal" integer,
  "IndEstatus" integer,
  "IndUsarCarnet" integer,
  "Fotografia" bytea,
  "IdCargo" integer,
  "NumeroCarnet" text,
  "Nacionalidad" text,
  "IndUsuarioAplicacion" text,
  "MarcajeInterDiario" boolean
)
LANGUAGE sql
STABLE
AS $$
  SELECT
    t."Cedula",
    t."Codigo",
    t."Nombre"::text AS "Nombres",
    ''::text AS "Apellidos",
    t."FechaIngreso",
    t."FechaNacimiento",
    t."Direccion"::text,
    t."Telefono"::text,
    t."Celular"::text,
    0 AS "IdPersonal",
    0 AS "IndEstatus",
    0 AS "IndUsarCarnet",
    NULL::bytea AS "Fotografia",
    0 AS "IdCargo",
    NULL::text AS "NumeroCarnet",
    NULL::text AS "Nacionalidad",
    NULL::text AS "IndUsuarioAplicacion",
    t."MarcajeInterDiario"
  FROM dbo."TRABAJADORES" t
  WHERE t."Status" = 1
    AND t."Cedula" = coalesce(p_idpersonal, t."Cedula");
$$;

CREATE OR REPLACE FUNCTION dbo."ObtenerAccesoPorFecha"(
  p_idpersonal varchar(15),
  p_fecha timestamp(0) without time zone
)
RETURNS TABLE(
  "IdControlAcceso" integer,
  "Cedula" varchar(15),
  "Fecha" date,
  "HoraEntrada" timestamp(0) without time zone,
  "IdPatronEntrada" integer,
  "FotografiaEntrada" bytea,
  "HoraSalida" timestamp(0) without time zone,
  "IdPatronSalida" integer,
  "FotografiaSalida" bytea,
  "IdZonaHoraria" integer,
  "IndUsoCarnet" integer
)
LANGUAGE sql
STABLE
AS $$
  SELECT
    c."Numero" AS "IdControlAcceso",
    c."Cedula",
    c."Fecha",
    c."HoraEntrada",
    0 AS "IdPatronEntrada",
    NULL::bytea AS "FotografiaEntrada",
    c."HoraSalida",
    0 AS "IdPatronSalida",
    NULL::bytea AS "FotografiaSalida",
    0 AS "IdZonaHoraria",
    0 AS "IndUsoCarnet"
  FROM dbo."CONTROLACCESO" c
  WHERE c."Cedula" = p_idpersonal
  ORDER BY "IdControlAcceso" DESC
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION dbo."ObtenerUltimoAccesoMarcaje"()
RETURNS TABLE(
  "IdControlAcceso" integer,
  "HoraEntrada" timestamp(0) without time zone,
  "HoraSalida" timestamp(0) without time zone
)
LANGUAGE sql
STABLE
AS $$
  SELECT c."Numero" AS "IdControlAcceso", c."HoraEntrada", c."HoraSalida"
  FROM dbo."CONTROLACCESO" c
  ORDER BY c."Numero" DESC
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION dbo."ObtenerUltimosAccesos"(p_idpersonal integer)
RETURNS TABLE(
  "IdDetalleControlAcceso" bigint,
  "Nombres" text,
  "TipoMarcaje" text,
  "Fecha" timestamp(0) without time zone
)
LANGUAGE sql
STABLE
AS $$
  SELECT
    d."IdDetalleControlAcceso",
    trim(t."Nombre")::text AS "Nombres",
    CASE WHEN d."IndTipoMarcaje" = 0 THEN 'ENTRADA' ELSE 'SALIDA' END::text AS "TipoMarcaje",
    d."Fecha"
  FROM dbo."DETALLECONTROLACCESO" d
  INNER JOIN dbo."TRABAJADORES" t ON t."Cedula" = d."IdPersonal"
  WHERE d."Fecha"::date = CURRENT_DATE
    AND (d."IdPersonal" = p_idpersonal::text OR t."Cedula" = p_idpersonal::text)
  ORDER BY d."Fecha" DESC
  LIMIT 4;
$$;

CREATE OR REPLACE FUNCTION dbo."sp_CompararTomasFisicas"()
RETURNS TABLE(
  "TipoDiferencia" text,
  "CodigoBarra" varchar(15),
  "Nombre" text,
  "TotalRegistrosEnToma1" bigint,
  "TotalRegistrosEnToma2" bigint,
  "TotalCantidadEnToma1" numeric(24,4),
  "TotalCantidadEnToma2" numeric(24,4),
  "DiferenciaDeConteoDeFilas" bigint,
  "DiferenciaDeCantidad" numeric(24,4),
  "PaginasEnToma1" text,
  "PaginasEnToma2" text
)
LANGUAGE sql
STABLE
AS $$
  WITH m1 AS (
    SELECT
      m."CodigoBarra",
      count(*)::bigint AS "TotalRows",
      coalesce(sum(m."Cantidad"), 0)::numeric(24,4) AS "TotalQuantity",
      string_agg(DISTINCT m."NumeroPagina"::text, ', ' ORDER BY m."NumeroPagina"::text) AS "Paginas"
    FROM dbo."MOVTOMAFISICA1" m
    GROUP BY m."CodigoBarra"
  ),
  m2 AS (
    SELECT
      m."CodigoBarra",
      count(*)::bigint AS "TotalRows",
      coalesce(sum(m."Cantidad"), 0)::numeric(24,4) AS "TotalQuantity",
      string_agg(DISTINCT m."NumeroPagina"::text, ', ' ORDER BY m."NumeroPagina"::text) AS "Paginas"
    FROM dbo."MOVTOMAFISICA2" m
    GROUP BY m."CodigoBarra"
  )
  SELECT
    'Solo en Toma Fisica 1'::text AS "TipoDiferencia",
    m1."CodigoBarra",
    coalesce(i."Nombre", 'NO EXISTEN EN INVENTARIO')::text AS "Nombre",
    m1."TotalRows" AS "TotalRegistrosEnToma1",
    m2."TotalRows" AS "TotalRegistrosEnToma2",
    m1."TotalQuantity" AS "TotalCantidadEnToma1",
    m2."TotalQuantity" AS "TotalCantidadEnToma2",
    NULL::bigint AS "DiferenciaDeConteoDeFilas",
    NULL::numeric(24,4) AS "DiferenciaDeCantidad",
    m1."Paginas" AS "PaginasEnToma1",
    m2."Paginas" AS "PaginasEnToma2"
  FROM m1
  LEFT JOIN m2 ON m1."CodigoBarra" = m2."CodigoBarra"
  LEFT JOIN dbo."INVENTARIO" i ON m1."CodigoBarra" = i."CodigoBarra"
  WHERE m2."CodigoBarra" IS NULL

  UNION ALL

  SELECT
    'Solo en Toma Fisica 2'::text AS "TipoDiferencia",
    m2."CodigoBarra",
    coalesce(i."Nombre", 'NO EXISTEN EN INVENTARIO')::text AS "Nombre",
    coalesce(m1."TotalRows", 0) AS "TotalRegistrosEnToma1",
    m2."TotalRows" AS "TotalRegistrosEnToma2",
    coalesce(m1."TotalQuantity", 0)::numeric(24,4) AS "TotalCantidadEnToma1",
    m2."TotalQuantity" AS "TotalCantidadEnToma2",
    NULL::bigint AS "DiferenciaDeConteoDeFilas",
    NULL::numeric(24,4) AS "DiferenciaDeCantidad",
    m1."Paginas" AS "PaginasEnToma1",
    m2."Paginas" AS "PaginasEnToma2"
  FROM m1
  RIGHT JOIN m2 ON m1."CodigoBarra" = m2."CodigoBarra"
  LEFT JOIN dbo."INVENTARIO" i ON m2."CodigoBarra" = i."CodigoBarra"
  WHERE m1."CodigoBarra" IS NULL

  UNION ALL

  SELECT
    'Desajuste'::text AS "TipoDiferencia",
    m1."CodigoBarra",
    coalesce(i."Nombre", 'NO EXISTEN EN INVENTARIO')::text AS "Nombre",
    m1."TotalRows" AS "TotalRegistrosEnToma1",
    m2."TotalRows" AS "TotalRegistrosEnToma2",
    m1."TotalQuantity" AS "TotalCantidadEnToma1",
    m2."TotalQuantity" AS "TotalCantidadEnToma2",
    (m1."TotalRows" - m2."TotalRows")::bigint AS "DiferenciaDeConteoDeFilas",
    (m1."TotalQuantity" - m2."TotalQuantity")::numeric(24,4) AS "DiferenciaDeCantidad",
    m1."Paginas" AS "PaginasEnToma1",
    m2."Paginas" AS "PaginasEnToma2"
  FROM m1
  INNER JOIN m2 ON m1."CodigoBarra" = m2."CodigoBarra"
  LEFT JOIN dbo."INVENTARIO" i ON m1."CodigoBarra" = i."CodigoBarra"
  WHERE m1."TotalRows" <> m2."TotalRows"
     OR coalesce(m1."TotalQuantity", 0) <> coalesce(m2."TotalQuantity", 0)
  ORDER BY 1, 2;
$$;

CREATE OR REPLACE PROCEDURE dbo."ActualizarMovimientoFisicologico"()
LANGUAGE plpgsql
AS $$
DECLARE
  v_fechahasta date;
  v_fechadesde date;
BEGIN
  SELECT coalesce(max(x."FechaAjuste"), DATE '1900-01-01') INTO v_fechahasta
  FROM (SELECT DISTINCT "FechaAjuste" FROM dbo."FISICOLOGICO") x;

  SELECT coalesce(max(x."FechaAjuste"), DATE '1900-01-01') INTO v_fechadesde
  FROM (
    SELECT DISTINCT "FechaAjuste"
    FROM dbo."FISICOLOGICO"
    WHERE "FechaAjuste" < v_fechahasta
  ) x;

  IF to_char(v_fechadesde, 'YYYYMMDD') <> '19000101' THEN
    v_fechadesde := v_fechadesde + 1;
  END IF;

  UPDATE dbo."FISICOLOGICO"
  SET "ConMovimiento" = 0
  WHERE "FechaAjuste" BETWEEN (v_fechadesde - 1) AND v_fechahasta;

  UPDATE dbo."FISICOLOGICO" fs
  SET "ConMovimiento" = 1
  WHERE fs."FechaAjuste" BETWEEN (v_fechadesde - 1) AND v_fechahasta
    AND EXISTS (
      SELECT 1
      FROM (
        SELECT DISTINCT mv."CodigoBarra"
        FROM dbo."MOVVENTAS" mv
        INNER JOIN dbo."FISICOLOGICO" f1
          ON f1."CodigoBarra" = mv."CodigoBarra"
         AND f1."FechaAjuste" BETWEEN (v_fechadesde - 1) AND v_fechahasta
        WHERE mv."Hora"::date BETWEEN v_fechadesde AND v_fechahasta

        UNION

        SELECT DISTINCT mv."CodigoBarra"
        FROM dbo."MOVDEVVENTAS" mv
        INNER JOIN dbo."FISICOLOGICO" f2
          ON f2."CodigoBarra" = mv."CodigoBarra"
         AND f2."FechaAjuste" BETWEEN (v_fechadesde - 1) AND v_fechahasta
        WHERE mv."Hora"::date BETWEEN v_fechadesde AND v_fechahasta

        UNION

        SELECT DISTINCT ma."CodigoBarra"
        FROM dbo."AJUSTES" aj
        INNER JOIN dbo."MOVAJUSTES" ma ON aj."Numero" = ma."Numero"
        INNER JOIN dbo."FISICOLOGICO" f3
          ON f3."CodigoBarra" = ma."CodigoBarra"
         AND f3."FechaAjuste" BETWEEN (v_fechadesde - 1) AND v_fechahasta
        WHERE aj."Fecha"::date BETWEEN v_fechadesde AND v_fechahasta

        UNION

        SELECT DISTINCT mc."CodigoBarra"
        FROM dbo."COMPRAS" co
        INNER JOIN dbo."MOVCOMPRAS" mc ON co."Documento" = mc."Documento" AND co."Proveedor" = mc."Proveedor"
        INNER JOIN dbo."FISICOLOGICO" f4
          ON f4."CodigoBarra" = mc."CodigoBarra"
         AND f4."FechaAjuste" BETWEEN (v_fechadesde - 1) AND v_fechahasta
        WHERE co."Fecha"::date BETWEEN v_fechadesde AND v_fechahasta

        UNION

        SELECT DISTINCT mt."CodigoBarra"
        FROM dbo."TRANSFERENCIAS" tr
        INNER JOIN dbo."MOVTRANSFERENCIAS" mt ON tr."Numero" = mt."Numero"
        INNER JOIN dbo."FISICOLOGICO" f5
          ON f5."CodigoBarra" = mt."CodigoBarra"
         AND f5."FechaAjuste" BETWEEN (v_fechadesde - 1) AND v_fechahasta
        WHERE tr."Fecha"::date BETWEEN v_fechadesde AND v_fechahasta

        UNION

        SELECT DISTINCT mt."CodigoBarra"
        FROM dbo."ITRANSFERENCIAS" tr
        INNER JOIN dbo."IMOVTRANSFERENCIAS" mt ON tr."Numero" = mt."Numero" AND tr."CodigoEnvia" = mt."CodigoEnvia"
        INNER JOIN dbo."FISICOLOGICO" f6
          ON f6."CodigoBarra" = mt."CodigoBarra"
         AND f6."FechaAjuste" BETWEEN (v_fechadesde - 1) AND v_fechahasta
        WHERE tr."Fecha"::date BETWEEN v_fechadesde AND v_fechahasta
      ) data
      WHERE data."CodigoBarra" = fs."CodigoBarra"
    );
END;
$$;

CREATE OR REPLACE PROCEDURE dbo."UpdateDispositivoMarcaje"(
  p_id integer,
  p_modelo varchar(500),
  p_marca varchar(500),
  p_tipo varchar(500),
  p_imagen bytea,
  p_idgrupo integer
)
LANGUAGE plpgsql
AS $$
BEGIN
  UPDATE dbo."DISPOSITIVOSMARCAJE"
  SET "Modelo" = coalesce(p_modelo, "Modelo"),
      "Marca" = coalesce(p_marca, "Marca"),
      "Tipo" = coalesce(p_tipo, "Tipo"),
      "Imagen" = p_imagen,
      "IdGrupo" = coalesce(p_idgrupo, "IdGrupo")
  WHERE "Id" = p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE dbo."UpdateDispositivoMarcajeConf"(
  p_id integer,
  p_iddispositivo integer,
  p_dispositivo varchar(500)
)
LANGUAGE plpgsql
AS $$
BEGIN
  UPDATE dbo."CONFIGURACIONMARCAJE"
  SET "IdDispositivo" = coalesce(p_iddispositivo, "IdDispositivo"),
      "Dispositivo" = coalesce(p_dispositivo, "Dispositivo")
  WHERE "Id" = p_id;
END;
$$;

-- -----------------------------------------------------------------------------
-- sysdiagrams compatibility routines
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION dbo."sp_creatediagram"(
  p_diagramname varchar(128),
  p_owner_id integer DEFAULT NULL,
  p_version integer DEFAULT NULL,
  p_definition bytea DEFAULT NULL
)
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
  v_owner_id integer := coalesce(p_owner_id, 1);
  v_retval integer;
BEGIN
  IF p_version IS NULL OR p_diagramname IS NULL THEN
    RETURN -1;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM dbo."sysdiagrams"
    WHERE "principal_id" = v_owner_id
      AND "name" = p_diagramname
  ) THEN
    RETURN -2;
  END IF;

  INSERT INTO dbo."sysdiagrams" ("name", "principal_id", "version", "definition")
  VALUES (p_diagramname, v_owner_id, p_version, p_definition)
  RETURNING "diagram_id" INTO v_retval;

  RETURN v_retval;
END;
$$;

CREATE OR REPLACE FUNCTION dbo."sp_alterdiagram"(
  p_diagramname varchar(128),
  p_owner_id integer DEFAULT NULL,
  p_version integer DEFAULT NULL,
  p_definition bytea DEFAULT NULL
)
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
  v_owner_id integer := coalesce(p_owner_id, 1);
BEGIN
  IF p_diagramname IS NULL THEN
    RETURN -1;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM dbo."sysdiagrams"
    WHERE "principal_id" = v_owner_id
      AND "name" = p_diagramname
  ) THEN
    RETURN -3;
  END IF;

  UPDATE dbo."sysdiagrams"
  SET "definition" = coalesce(p_definition, "definition"),
      "version" = coalesce(p_version, "version")
  WHERE "principal_id" = v_owner_id
    AND "name" = p_diagramname;

  RETURN 0;
END;
$$;

CREATE OR REPLACE FUNCTION dbo."sp_dropdiagram"(
  p_diagramname varchar(128),
  p_owner_id integer DEFAULT NULL
)
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
  v_owner_id integer := coalesce(p_owner_id, 1);
BEGIN
  IF p_diagramname IS NULL THEN
    RETURN -1;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM dbo."sysdiagrams"
    WHERE "principal_id" = v_owner_id
      AND "name" = p_diagramname
  ) THEN
    RETURN -3;
  END IF;

  DELETE FROM dbo."sysdiagrams"
  WHERE "principal_id" = v_owner_id
    AND "name" = p_diagramname;

  RETURN 0;
END;
$$;

CREATE OR REPLACE FUNCTION dbo."sp_helpdiagramdefinition"(
  p_diagramname varchar(128),
  p_owner_id integer DEFAULT NULL
)
RETURNS TABLE("version" integer, "definition" bytea)
LANGUAGE sql
STABLE
AS $$
  SELECT s."version", s."definition"
  FROM dbo."sysdiagrams" s
  WHERE s."name" = p_diagramname
    AND s."principal_id" = coalesce(p_owner_id, 1)
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION dbo."sp_helpdiagrams"(
  p_diagramname varchar(128) DEFAULT NULL,
  p_owner_id integer DEFAULT NULL
)
RETURNS TABLE(
  "Database" text,
  "Name" varchar(128),
  "ID" integer,
  "Owner" text,
  "OwnerID" integer
)
LANGUAGE sql
STABLE
AS $$
  SELECT
    current_database()::text AS "Database",
    s."name" AS "Name",
    s."diagram_id" AS "ID",
    s."principal_id"::text AS "Owner",
    s."principal_id" AS "OwnerID"
  FROM dbo."sysdiagrams" s
  WHERE (p_diagramname IS NULL OR s."name" = p_diagramname)
    AND (p_owner_id IS NULL OR s."principal_id" = p_owner_id)
  ORDER BY 4, 5, 1;
$$;

CREATE OR REPLACE FUNCTION dbo."sp_renamediagram"(
  p_diagramname varchar(128),
  p_owner_id integer DEFAULT NULL,
  p_new_diagramname varchar(128) DEFAULT NULL
)
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
  v_owner_id integer := coalesce(p_owner_id, 1);
  v_diag_id integer;
  v_target_id integer;
BEGIN
  IF p_diagramname IS NULL OR p_new_diagramname IS NULL THEN
    RETURN -1;
  END IF;

  SELECT s."diagram_id" INTO v_diag_id
  FROM dbo."sysdiagrams" s
  WHERE s."principal_id" = v_owner_id
    AND s."name" = p_diagramname
  LIMIT 1;

  IF v_diag_id IS NULL THEN
    RETURN -3;
  END IF;

  SELECT s."diagram_id" INTO v_target_id
  FROM dbo."sysdiagrams" s
  WHERE s."principal_id" = v_owner_id
    AND s."name" = p_new_diagramname
  LIMIT 1;

  IF v_target_id IS NOT NULL AND v_target_id <> v_diag_id THEN
    RETURN -2;
  END IF;

  UPDATE dbo."sysdiagrams"
  SET "name" = p_new_diagramname
  WHERE "diagram_id" = v_diag_id;

  RETURN 0;
END;
$$;

CREATE OR REPLACE FUNCTION dbo."sp_upgraddiagrams"()
RETURNS integer
LANGUAGE plpgsql
AS $$
BEGIN
  IF to_regclass('dbo.sysdiagrams') IS NOT NULL THEN
    RETURN 0;
  END IF;

  EXECUTE '
    CREATE TABLE dbo."sysdiagrams" (
      "name" varchar(128) NOT NULL,
      "principal_id" integer NOT NULL,
      "diagram_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "version" integer,
      "definition" bytea
    )';

  EXECUTE 'CREATE UNIQUE INDEX "UK_principal_name" ON dbo."sysdiagrams" ("principal_id", "name")';
  RETURN 1;
END;
$$;
