import { EntidadDestino } from "./entidades";

// Columnas legacy confirmadas contra apps/api/prisma/schema.prisma que
// determinan hash_registro. El orden es fijo (no alfabetico) para que el
// hash sea deterministico entre corridas; cambiar el orden invalida todo el
// historial de hashes ya calculado, no reordenar sin migrar.

export const HASH_WHITELIST: Record<EntidadDestino, readonly string[]> = {
  DIM_ARTICULOS_HIST: [
    "Referencia",
    "Nombre",
    "CodigoMarca",
    "Talla",
    "CodigoColor",
    "Fabricante",
    "Categoria",
    "TipoImpuesto",
    "Tipo",
    "Serializado",
    "CodigoBarraAnt",
    "Status",
  ],
  DIM_CLIENTES_HIST: ["Nombre", "FechaIngreso", "Telefono", "Direccion", "Status", "Tipo", "TipoContribuyente"],
  HECH_INVENTARIO_HIST: [
    "Existencia",
    "ExistenciaInicial",
    "PuntoReorden",
    "PrecioDetal",
    "PrecioMayor",
    "PrecioAfiliado",
    "PrecioPromocion",
    "CostoInicial",
    "CostoPromedio",
    "UltimoCosto",
    "CostoDolar",
    "Promocion",
    "FechaInicial",
    "FechaFinal",
  ],
  HECH_VENTAS_HIST: [
    "Fecha",
    "Vendedor",
    "Cliente",
    "TipoVenta",
    "FormaPago",
    "DiasCredito",
    "TotalMercancia",
    "TotalDescuento",
    "TotalImpuesto",
    "TotalCosto",
    "InterContable",
    "Usuario",
    "Status",
    "NumeroOrden",
    "TotalPago",
    "TotalDolares",
    "TasaCambio",
    "Estacion",
    "TotalDolaresE",
    "TasaIGTF",
    "MontoIGTF",
    "BaseImponibleIGTF",
  ],
  HECH_VENTAS_DETALLE_HIST: [
    "Hora",
    "TipoLista",
    "CodigoBarra",
    "Precio",
    "PrecioLista",
    "Costo",
    "Impuesto",
    "PorcentajeImpuesto",
    "Cantidad",
    "CantidadDevuelta",
    "PorcentajeDescuento",
    "PrecioDetal",
    "Regla",
    "IDRegla",
  ],
  HECH_PAGOS_HIST: [
    "FormaPago",
    "Fecha",
    "Documento",
    "Aprobacion",
    "Banco",
    "PuntoVenta",
    "Monto",
    "Status",
    "JSON_Merchant",
    "MontoDivisa",
    "FormaPagoOriginal",
  ],
  HECH_CAJAS_HIST: [
    "Numero",
    "FacturaInicial",
    "FacturaFinal",
    "PorcentajeImpuesto",
    "HoraApertura",
    "HoraCierre",
    "NumeroReporteZ",
    "Status",
    "ReporteZTexto",
    "Acumulado",
  ],
};
