export const PRICE_CHANGE_MODE_SELECTED_ITEMS = "SELECTED_ITEMS";
export const PRICE_CHANGE_MODE_FULL_INVENTORY = "FULL_INVENTORY";

export type PriceChangeMode = typeof PRICE_CHANGE_MODE_SELECTED_ITEMS | typeof PRICE_CHANGE_MODE_FULL_INVENTORY;

export const PRICE_CHANGE_MODES: PriceChangeMode[] = [
  PRICE_CHANGE_MODE_SELECTED_ITEMS,
  PRICE_CHANGE_MODE_FULL_INVENTORY,
];
